In [2]:
import os
import pandas as pd
import requests
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
from dotenv import load_dotenv

In [3]:
#Visualiza la informacion completa 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Acceso a la API de YELP

In [4]:
# Carga las variables del archivo .env
load_dotenv()

# URL de la API
api_url = 'https://api.yelp.com/v3/businesses/search'

# credenciales de forma segura
clientid = os.getenv('YELP_CLIENT_ID')
apikey = os.getenv('YELP_API_KEY')

# Configuracion headers 
headers = {'Authorization': f'Bearer {apikey}'}

Extracción de datos para una ciudad

In [5]:
ciudad = "Denver" # Se puede elegir cualquier ciudad del dataset entregado

In [6]:
# De esta manera se consulta el API de Yelp para obtener información sobre restaurantes en la ciudad especificada
#Sólo se extraen las columnas de interes, que puden aportar valor al análisis
Complete_list = []
#Solo se permiten descargar de 50 datos hasta un max de 240 por eso se hace un ciclo
for i in range(0, 200 ,50):
    params={'term':'restaurants','location': ciudad,'limit':50, 'offset':i }
    response=requests.get(api_url,params=params,headers=headers)
    data=response.json()
    
    for info in data['businesses']:
        buffer = []
        buffer.append(info.get('id', None))
        buffer.append(info.get('name', None))
        buffer.append(info.get('is_closed',None))
        buffer.append(info.get('review_count',None))
        
        #Desempaquetar las que tiene los diccionarios dentro
        categories = info.get('categories', [])#'categories'
        if categories and isinstance(categories, list):
            principal_categories = categories[0].get('title',None)
        else:
            principal_categories = None
        buffer.append(principal_categories)
        
        buffer.append(info.get('rating',None))
        
        coordinates = info.get('coordinates')
        buffer.append(coordinates.get('latitude',None))
        buffer.append(coordinates.get('longitude',None))
        
        #Transacciones tambien se desenglozan 3 posibles opciones delivery, pick up y reservation
        trans = info.get('transactions',[])
        #Para delivery
        buffer.append('yes' if 'delivery' in trans else 'No')
        #Para reservasión
        buffer.append('yes' if 'restaurant_reservation' in trans else 'No')
        #Para 
        buffer.append('yes' if 'pickup' in trans else 'No')
       
        
        #equivalencia para los price
        
        buffer.append(info.get('price',None))

        site = info.get('location',{})
        buffer.append(site.get('city'))

        buffer.append(info.get('phone', None))
        buffer.append(info.get('display_phone', None))
        
        Complete_list.append(buffer)

    
print(Complete_list)

[['GmniFxffmpFcbmb5KWIwbA', 'Culinary Dropout', False, 1038, 'New American', 4.2, 39.73132, -104.93918, 'No', 'No', 'No', '$$', 'Denver', '+17207790190', '(720) 779-0190'], ['Y-c9rFdGYXlT-A1ndoCTrg', 'Tavernetta', False, 990, 'Italian', 4.5, 39.75302254234153, -105.00196807402817, 'yes', 'No', 'yes', '$$$', 'Denver', '+17206051889', '(720) 605-1889'], ['UkXP_D2vih-LS5oAaMxRIg', 'Madeline', False, 20, 'Restaurants', 4.9, 39.725727, -104.97143, 'No', 'No', 'No', None, 'Denver', '', ''], ['lyit8GGKG4AyxO3CrTQErQ', 'Jack’s Modern Steakhouse', False, 252, 'Bars', 4.6, 39.68985, -104.980581, 'No', 'No', 'No', '$$$', 'Denver', '+17208685800', '(720) 868-5800'], ['2wrS0h8iXFZTr4p0egCLjQ', 'West Saloon & Kitchen ', False, 1098, 'American', 4.5, 39.74403, -104.99044, 'yes', 'yes', 'yes', '$$', 'Denver', '+13038253690', '(303) 825-3690'], ['svJWwW0ilssyqk_UML0mUg', 'Work & Class', False, 1893, 'New American', 4.5, 39.75761, -104.98604, 'yes', 'No', 'No', '$$', 'Denver', '+13032920700', '(303) 292-0700'], ['0jTb4q8Ezil_tXkbZf-HRQ', 'Rougarou', False, 59, 'Southern', 4.7, 39.75624, -104.97592, 'No', 'No', 'No', None, 'Denver', '', ''], ['ywFvkNZVJoXUQbZoq7fr1w', 'Rioja', False, 2930, 'New American', 4.3, 39.7478083125095, -104.999331349925, 'No', 'No', 'yes', '$$$', 'Denver', '+13038202282', '(303) 820-2282'], ['i8VF3q7dTszCcigJSMcJzQ', 'Angelo’s Taverna', False, 2033, 'Italian', 4.4, 39.725523, -104.979224, 'yes', 'No', 'yes', '$$', 'Denver', '+13037443366', '(303) 744-3366'], ['iS9j0iSOhRzBBYJdzzuZFQ', 'Point Easy', False, 94, 'New American', 4.6, 39.75688, -104.96322, 'No', 'No', 'No', None, 'Denver', '+13032335656', '(303) 233-5656'], ['jML03gtMkgIFWX9Iium4Xg', 'Safta', False, 1089, 'Middle Eastern', 4.4, 39.76893587969719, -104.98035233356602, 'yes', 'No', 'No', '$$$', 'Denver', '+17204082444', '(720) 408-2444'], ['x0rVT3E__00xg99uGr0tjg', 'Happy Camper', False, 1232, 'Pizza', 4.2, 39.76223, -105.00676, 'yes', 'No', 'yes', '$$', 'Denver', '+17202591044', '(720) 259-1044'], ['InKe17J_fpqDBorFxEsUXw', "Ma's Kitchen Next Door", False, 78, 'Pan Asian', 4.7, 39.740336, -104.95957, 'No', 'No', 'No', None, 'Denver', '+13037368037', '(303) 736-8037'], ['gagUrh3806qc5hZ14F0Odw', 'Denver Biscuit Co. - Colfax', False, 4998, 'Sandwiches', 4.5, 39.74034, -104.949128, 'yes', 'No', 'yes', '$$', 'Denver', '+13033393977', '(303) 339-3977'], ['fHR1VVGarB17xh56bxbUcg', 'Revival Denver Public House', False, 247, 'Cocktail Bars', 4.1, 39.74311852120664, -104.9789215, 'yes', 'No', 'yes', None, 'Denver', '+17205247867', '(720) 524-7867'], ['vFNCul1JCv4yBtTqdoxscQ', 'Olivia', False, 310, 'Italian', 4.6, 39.71126870628247, -104.97318201165669, 'yes', 'No', 'No', None, 'Denver', '+13039990395', '(303) 999-0395'], ['XlNLa_kiknuAfm29wXO8KA', 'Pig and Tiger', False, 65, 'Taiwanese', 4.4, 39.75082, -104.9847, 'No', 'No', 'No', None, 'Denver', '+17206967979', '(720) 696-7979'], ['YxeTWblmRB3m7egJzgAJCg', 'Pony Up', False, 480, 'Sandwiches', 4.5, 39.75242, -104.99625, 'yes', 'No', 'yes', '$$', 'Denver', '+17207108144', '(720) 710-8144'], ['Xksk_U8F756DUVFCz134Tw', "The Wolf's Tailor", False, 337, 'New American', 4.4, 39.77277, -105.01088, 'yes', 'No', 'yes', '$$$$', 'Denver', '+17204566705', '(720) 456-6705'], ['UxCQdVtMhGSiZrcGJd12Ig', 'Alma Fonda Fina', False, 308, 'Mexican', 4.7, 39.758115, -105.01167, 'No', 'No', 'No', None, 'Denver', '+13034559463', '(303) 455-9463'], ['LX8nS1dlW7MEZDDEmVcyGw', 'Root Down', False, 4192, 'New American', 4.4, 39.76306, -105.0056, 'yes', 'No', 'No', '$$', 'Denver', '+13039934200', '(303) 993-4200'], ['6-MYTEofJo7jmdoTfuVIHA', "Nana's Dim Sum & Dumplings", False, 645, 'Dim Sum', 4.5, 39.763536, -105.010744, 'yes', 'No', 'yes', None, 'Denver', '+17207694051', '(720) 769-4051'], ['h5ohyi4dOsioSsvSj3398A', 'Monarch', False, 8, 'Pizza', 5.0, 39.74304, -104.984005, 'No', 'No', 'No', None, 'Denver', '', ''], ['pFuMzFgNKdEWXi0ckj0ivw', 'Corsica Wine Bar', False, 261, 'Wine Bars', 4.3, 39.761415097958434, -104.98389661226847, 'No', 'No', 'No', None, 'Denver', '+17209942020', '(720) 994-2020'], ['0-O-xCaxbO-ftWVEYVrRlg', 'Barcelona Wine Bar', False, 1269, 'Tapas/Small Plates', 4.3, 39.761334329900365, -104.98136061794014, 'yes', 'No', 'No', '$$', 'Denver', '+13038163300', '(303) 816-3300'], ['kRiwvntcXKDPdtpYKcGPhg', 'Onefold', False, 1245, 'Breakfast & Brunch', 4.3, 39.74466, -104.96934, 'yes', 'No', 'yes', '$$', 'Denver', '+13039540877', '(303) 954-0877'], ['6F4_oM9oRzBDc7KeTEtvcw', 'Wild Corgi Pub', False, 149, 'Pubs', 4.3, 39.73697, -104.97226, 'yes', 'No', 'yes', None, 'Denver', '+13038327636', '(303) 832-7636'], ['PHs8DL9UUOOehhUtE5b1qw', 'Corinne Denver', False, 766, 'Breakfast & Brunch', 4.0, 39.744067916552, -104.9939493, 'yes', 'No', 'yes', '$$', 'Denver', '+17209961555', '(720) 996-1555'], ['L3uHyn2eMYOur3CRLkg8sA', 'Mezcaleria Alma', False, 117, 'Wine Bars', 4.8, 39.758050103395476, -105.01159530133009, 'No', 'No', 'No', None, 'Denver', '+13034841471', '(303) 484-1471'], ['SND7k63zO_UuV-Sr--knpA', 'Painted RiNo Kitchen + Bar', False, 10, 'Breakfast & Brunch', 4.3, 39.77166, -104.977695, 'No', 'No', 'No', None, 'Denver', '+17208067251', '(720) 806-7251'], ['KeRN5k0IFBEdGhDTRNZe_g', 'The Porchetta House', False, 165, 'Sandwiches', 4.7, 39.7403994, -104.9694149, 'yes', 'No', 'yes', '$$', 'Denver', '+13038617333', '(303) 861-7333'], ['EjNI-dNAMrYxKgUIkqeqhg', 'Guard and Grace Modern Steakhouse', False, 2135, 'Steakhouses', 4.5, 39.7479555, -104.98907520429918, 'yes', 'No', 'yes', '$$$$', 'Denver', '+13032938500', '(303) 293-8500'], ['QWWfOQ9yrWDuZwP-mgL1Ig', 'Lucina Eatery & Bar', False, 170, 'Latin American', 4.6, 39.75017, -104.91776, 'No', 'No', 'No', '$$$', 'Denver', '+17208141053', '(720) 814-1053'], ['rdZPV9r3WPlke0ZO1mRcNA', "Pete's Kitchen", False, 971, 'Greek', 3.9, 39.739781, -104.963662, 'No', 'No', 'yes', '$$', 'Denver', '+13033213139', '(303) 321-3139'], ['R5sNCLBmMp61uYui1Wp5UA', 'Toki Ramen And Sushi', False, 35, 'Ramen', 4.9, 39.69141345932811, -104.94037188552952, 'yes', 'No', 'yes', None, 'Denver', '', ''], ['LLxpJh4yyExw1K7GJsB2zw', 'A5 Steakhouse', False, 321, 'Steakhouses', 4.3, 39.75027916485665, -105.00154875218868, 'No', 'No', 'No', None, 'Denver', '+13036230534', '(303) 623-0534'], ['43DCpM0VKoFY-Mnv30RhLQ', 'Kyuu', False, 14, 'Japanese', 4.8, 39.7430538, -104.9711784, 'No', 'No', 'No', None, 'Denver', '+17207285226', '(720) 728-5226'], ['c3QuHjgIkESyn_eD4EiACA', 'Nocturne', False, 429, 'Jazz & Blues', 4.6, 39.7595901, -104.9845123, 'yes', 'No', 'No', '$$$', 'Denver', '+13032953333', '(303) 295-3333'], ['-mLKEN6U1vmBs8IxxBVaEw', 'Fish N Beer', False, 528, 'Seafood', 4.6, 39.76719859814876, -104.97402661349189, 'yes', 'No', 'No', '$$', 'Denver', '+13032483497', '(303) 248-3497'], ['FIabjV94L_-HH9w8rT6j3Q', 'Carne - Argentina Street Food', False, 116, 'Sandwiches', 4.7, 39.720497589455846, -104.99840753153383, 'yes', 'No', 'yes', '$$', 'Denver', '+17205103999', '(720) 510-3999'], ['qwklKpOZFgOOjMm3-NMzNA', 'BurnDown', False, 228, 'Bars', 4.1, 39.708036, -104.987242, 'No', 'No', 'No', '$$', 'Denver', '+17208993827', '(720) 899-3827'], ['NOkJ14ltntgE4XWS5AgOSA', 'The Brutal Poodle', False, 624, 'Bars', 4.5, 39.6808802, -104.9878461, 'yes', 'No', 'yes', '$$', 'Denver', '+17203796281', '(720) 379-6281'], ['7A70YVFJBWN6fbCYQPpNIA', 'Brasserie Brixton', False, 165, 'French', 4.4, 39.7683093620018, -104.966288432479, 'No', 'No', 'No', None, 'Denver', '+13035930951', '(303) 593-0951'], ['Lu6Uk12Rg0jkUQUzcHLWFw', 'Fox And The Hen', False, 429, 'Breakfast & Brunch', 4.4, 39.762136440691314, -105.01417444519963, 'No', 'No', 'No', '$$', 'Denver', '+13038626795', '(303) 862-6795'], ['s87TW7XplzOqu66TxIyw3g', 'Margot Denver', False, 58, 'New American', 4.7, 39.68844071564525, -104.9806203125336, 'No', 'No', 'No', None, 'Denver', '+17203908785', '(720) 390-8785'], ['GxCgbV8rB7ORs8g0J2nMwQ', 'Noodles By Nina', False, 145, 'Noodles', 4.5, 39.74290781479942, -104.9692528, 'No', 'No', 'No', '$$', 'Denver', '+13039555858', '(303) 955-5858'], ['MYs1Jc9wj3EjrL5TxR7x-g', 'Gabys German Eatery', False, 138, 'German', 4.5, 39.71241, -105.06312, 'yes', 'No', 'No', None, 'Lakewood', '+17203298188', '(720) 329-8188'], ['X3_hbxeKNXChhvnAF7RnRQ', '30Forth Kitchen', False, 6, 'New American', 5.0, 39.75876605502361, -104.9633876571782, 'No', 'No', 'No', None, 'Denver', '+17202278209', '(720) 227-8209'], ['ewCTNd0cUPMY32kD5opphw', 'Chubby Cattle Hotpot & Sushi - Denver', False, 1681, 'Hot Pot', 4.2, 39.716748, -104.987193, 'yes', 'No', 'yes', '$$$', 'Denver', '+17206502541', '(720) 650-2541'], ['CQNv4SXqFltcwNsx-qHbLQ', "Steuben's Uptown", False, 3476, 'Diners', 4.0, 39.74349, -104.98017, 'yes', 'No', 'yes', '$$', 'Denver', '+13038301001', '(303) 830-1001'], ['jVOAZe9L3Kwx9Ze-UhT3_w', 'Odyssey Italian Restaurant', False, 1536, 'Sicilian', 4.3, 39.7257806690032, -104.979706093254, 'yes', 'No', 'yes', '$$', 'Denver', '+13033180102', '(303) 318-0102'], ['zN55MOWDOYAUhJHRVBx9EA', 'Paperboy Denver', False, 72, 'Breakfast & Brunch', 4.3, 39.762003, -105.039149, 'No', 'No', 'No', None, 'Denver', '+17202794603', '(720) 279-4603'], ['JJiugrBcZrNpX0ueUBuvrg', 'Cherry Cricket - Cherry Creek', False, 3535, 'Burgers', 4.0, 39.719634, -104.956348, 'yes', 'No', 'yes', '$$', 'Denver', '+13033227666', '(303) 322-7666'], ['k1mGLPBSaUhZKem1KrXLJQ', 'Stout Street Social', False, 1747, 'New American', 4.0, 39.74428793417868, -104.99494696113614, 'yes', 'No', 'yes', '$$', 'Denver', '+17202149100', '(720) 214-9100'], ['ZnhMS3NichhkEPUmTqJfbw', 'Mantra cafe', False, 72, 'Indian', 4.6, 39.734877044559894, -104.9878108, 'yes', 'No', 'yes', None, 'Denver', '+17207615972', '(720) 761-5972'], ['8wmfcpBTOn6BwC1YPvOmDA', 'Rōmyō', False, 28, 'Italian', 4.3, 39.747612, -104.999843, 'No', 'No', 'No', None, 'Denver', '', ''], ['sU4K-0uTlhvn3OTGqnKamw', 'Heretik', False, 23, 'Spanish', 4.7, 39.759704419199366, -104.986211, 'No', 'No', 'No', None, 'Denver', '+17202579168', '(720) 257-9168'], ['yXVJ_K6vdpM3PwfHfkyn5g', 'Mister Oso', False, 501, 'Tacos', 4.1, 39.76424, -104.97848, 'yes', 'No', 'yes', '$$', 'Denver', '+17206776454', '(720) 677-6454'], ['NGiJYiciQao11MXwl-56pg', 'Kawa Ni', False, 254, 'Izakaya', 4.5, 39.761783162827754, -105.00996828834319, 'No', 'No', 'No', '$$$', 'Denver', '+17207123371', '(720) 712-3371'], ['lSndVTQ9XCpz9fDMFpSBug', 'Carne RiNo', False, 113, 'Steakhouses', 4.4, 39.7588, -104.9853, 'No', 'No', 'No', None, 'Denver', '+13039531558', '(303) 953-1558'], ['BHpQiNX5LF79RHTCng8TqQ', 'Nola Voodoo Tavern', False, 332, 'Cafes', 4.5, 39.764695, -104.960311, 'yes', 'No', 'yes', '$$', 'Denver', '+17203899544', '(720) 389-9544'], ['2gGWFWp3DIjxzE3lVFZtNA', 'Little Wolf', False, 50, 'Whiskey Bars', 4.8, 39.77709, -105.03444, 'No', 'No', 'No', None, 'Denver', '+17207039220', '(720) 703-9220'], ['VxSKu6BxKiT1jRr6arsLLg', 'Cherry Cricket - Downtown', False, 535, 'Sports Bars', 4.1, 39.756308, -104.99122, 'yes', 'No', 'No', '$$', 'Denver', '+13032973644', '(303) 297-3644'], ['DFzFzU6iHbXZtTGu1mN4IA', 'Stellar Jay', False, 72, 'Restaurants', 4.3, 39.74031528693361, -104.99094534025234, 'No', 'No', 'No', '$$$', 'Denver', '+13032566381', '(303) 256-6381'], ['tnFs9EImexnBdlwZjmEfcw', 'Horse & Tiger', False, 9, 'Comfort Food', 5.0, 39.778458, -104.98313, 'No', 'No', 'No', None, 'Denver', '+13033512377', '(303) 351-2377'], ['viYTcIvA2l_iSqrNpWeTdA', "Yahya's Mediterranean Grill & Pastries", False, 683, 'Mediterranean', 4.6, 39.740169467754185, -104.9607666, 'yes', 'No', 'yes', '$$', 'Denver', '+17205328746', '(720) 532-8746'], ['s0_kPOB-ywdGUMdqHw5uTg', 'Dearly Departed', False, 14, 'Cocktail Bars', 4.9, 39.759241, -105.010750860112, 'No', 'No', 'No', None, 'Denver', '+13034793124', '(303) 479-3124'], ['6VE5QY2ULcc8JHB-eLARag', 'Alteño', False, 100, 'Mexican', 4.5, 39.720399153311334, -104.95599780231714, 'No', 'No', 'No', None, 'Denver', '+13035324999', '(303) 532-4999'], ['_fcKVnAc2n2Nj5vX-vcLAA', 'Aguanile', False, 14, 'Puerto Rican', 4.6, 39.70869271594809, -104.9926253, 'No', 'No', 'No', None, 'Denver', '+13033515975', '(303) 351-5975'], ['u0lEXYd_cdf2_Zg99rSM9w', 'Vine Street Pub & Brewery', False, 1003, 'American', 4.2, 39.7434, -104.96201, 'No', 'No', 'No', '$$', 'Denver', '+13033882337', '(303) 388-2337'], ['fdipNvAALQxjJWNz-USidQ', 'Hillstone Restaurant', False, 780, 'New American', 3.7, 39.72114050238617, -104.95842376071349, 'No', 'No', 'yes', '$$$', 'Denver', '+13033334688', '(303) 333-4688'], ['biju9F9GKy0Ogn3YotSZ4A', 'Wildflower', False, 231, 'Cocktail Bars', 4.6, 39.767589, -105.003796, 'No', 'No', 'No', None, 'Denver', '+17207066615', '(720) 706-6615'], ['O2DoP-SUVov0qwAn1atMbg', 'Champagne Tiger', False, 79, 'French', 4.5, 39.740206, -104.979676, 'No', 'No', 'No', None, 'Denver', '+13039420593', '(303) 942-0593'], ['swPiklhuXaMLnw5Rh2y7Ew', 'Rhein Haus', False, 622, 'Bars', 3.7, 39.74835474, -105.00058487, 'yes', 'No', 'yes', '$$', 'Denver', '+13037315374', '(303) 731-5374'], ['gGXnG-Rf5UUr6wT8krXT5w', 'Williams & Graham', False, 1136, 'American', 4.4, 39.76195, -105.011, 'No', 'No', 'No', '$$', 'Denver', '+13039978886', '(303) 997-8886'], ['m3ifi6O7ntMta8102eVgow', 'Uchi Denver', False, 1140, 'Japanese', 4.5, 39.75692640406484, -104.98526144406438, 'yes', 'No', 'No', '$$$$', 'Denver', '+13034441922', '(303) 444-1922'], ['IHS_gAK8AEYKqs6RCQXSEw', 'Florence Supper Club', False, 58, 'Italian', 4.2, 39.70973, -104.98069, 'No', 'No', 'No', None, 'Denver', '', ''], ['OGwS_BIkHSWdcvQRdW_kfA', 'Four Friends Kitchen', False, 2217, 'Southern', 4.3, 39.7574776411057, -104.900571629405, 'yes', 'No', 'No', '$$', 'Denver', '+13033888299', '(303) 388-8299'], ['JRNo_7YSPyVBTMNpu8ZkLA', 'The Velvet Cellar', False, 118, 'Cocktail Bars', 4.4, 39.750965, -105.001631, 'No', 'No', 'No', '$$$', 'Denver', '+17206769116', '(720) 676-9116'], ['Z8vO_mf1V09QDUPdyqJ6og', 'Linger', False, 4438, 'Asian Fusion', 4.1, 39.75954, -105.01139, 'yes', 'No', 'yes', '$$', 'Denver', '+13039933120', '(303) 993-3120'], ['6fJltLxQcLgO0owitrzlBQ', 'Cuba Cuba Cafe & Bar', False, 1033, 'Cuban', 4.4, 39.7350845336914, -104.993179321289, 'yes', 'No', 'yes', '$$', 'Denver', '+13036052822', '(303) 605-2822'], ['pm-Rc3kcCuT5RGbNIldinA', 'Acova', False, 736, 'New American', 4.3, 39.7677766, -105.004247, 'yes', 'No', 'yes', '$$', 'Denver', '+13037362718', '(303) 736-2718'], ['uQd0TZKBprBXxF1aGSIAIA', 'Dew Drop Inn', False, 89, 'Gastropubs', 4.5, 39.7434, -104.9738192, 'No', 'No', 'No', None, 'Denver', '+17206124160', '(720) 612-4160'], ['T0oDpWqZWOjli02HuIO3DQ', 'Potager', False, 500, 'New American', 3.8, 39.73396, -104.97542, 'No', 'No', 'yes', '$$$', 'Denver', '+13038325788', '(303) 832-5788'], ['kI5oOBAGS-Vo4chwmgOVmQ', 'Cart-Driver', False, 830, 'Pizza', 4.5, 39.7575304532638, -104.98621389540216, 'yes', 'No', 'yes', '$$', 'Denver', '+13032923553', '(303) 292-3553'], ['nMagfV2RQrH0N0EZ46AHRg', 'Cimera', False, 71, 'Latin American', 3.7, 39.768434, -104.980181, 'No', 'No', 'No', None, 'Denver', '+17204676913', '(720) 467-6913'], ['_2vT7PH78NIqleshrnb19w', 'Brutø', False, 147, 'Tapas/Small Plates', 4.3, 39.752781, -104.996823, 'yes', 'No', 'yes', None, 'Denver', '+17203252195', '(720) 325-2195'], ['KwmKhdWpcIzypdjAUNrc7w', 'Mercantile', False, 1423, 'New American', 4.2, 39.7536149959513, -104.999707, 'yes', 'No', 'No', '$$', 'Denver', '+17204603733', '(720) 460-3733'], ['PUhHWM8_rbwUD-8gzfCSOg', 'Sắp Sửa', False, 252, 'Vietnamese', 4.3, 39.73979449902862, -104.95663650333881, 'No', 'No', 'No', None, 'Denver', '+13037362303', '(303) 736-2303'], ['WTe8uL6vF1ZuKAeJIvxR8w', "Savina's", False, 2222, 'Mexican', 4.1, 39.74475767699346, -104.9878270464936, 'yes', 'No', 'yes', '$$', 'Denver', '+13034338300', '(303) 433-8300'], ['QZAZrHljjy8qh1QXacT0tg', 'Olive & Finch', False, 945, 'New American', 4.2, 39.74306, -104.96892, 'yes', 'No', 'yes', '$$', 'Denver', '+13038328663', '(303) 832-8663'], ['XWqdMrdt8OJWT6ECMvavPw', 'The Plimoth', False, 406, 'Italian', 4.4, 39.7571433867367, -104.958879160049, 'yes', 'No', 'No', '$$$', 'Denver', '+13032971215', '(303) 297-1215'], ['HlL84_OVXvKHndkCqQJn2w', 'Kkoki Korean BBQ', False, 99, 'Korean', 4.6, 39.75435784136808, -105.0046521, 'No', 'No', 'No', None, 'Denver', '+13039532422', '(303) 953-2422'], ['wL04ets5vd2CGxbzj3ii5w', 'Blue Agave Grill', False, 851, 'Seafood', 4.1, 39.749031284444186, -104.99682466, 'yes', 'No', 'yes', '$$', 'Denver', '+17205508389', '(720) 550-8389'], ['46gG3_h3zwFfkf4_183Ydg', 'Somebody People', False, 362, 'Wine Bars', 4.5, 39.695218, -104.987801, 'yes', 'No', 'No', '$$$', 'Denver', '+17205025681', '(720) 502-5681'], ['izi7Hh5Kz7iC4gEjQ4BxSw', 'Dear Emilia', False, 35, 'Italian', 4.3, 39.772372, -104.978388, 'No', 'No', 'No', None, 'Denver', '', ''], ['zvxXmGRW464sEe-8TVrPGQ', 'Ni Tuyo', False, 198, 'Tacos', 4.6, 39.70278, -104.95911, 'No', 'No', 'No', '$$', 'Denver', '+13032828896', '(303) 282-8896'], ['bb_VNwJQLzao_3HSGx6B9g', 'Postino 9CO', False, 416, 'Wine Bars', 4.5, 39.7297736, -104.94027336212478, 'yes', 'No', 'yes', '$$', 'Denver', '+17202625474', '(720) 262-5474'], ['5lCzYPnAoNNlAZxW3rr_RA', "Satchel's on 6th", False, 233, 'New American', 3.9, 39.72545, -104.96674, 'yes', 'No', 'No', '$$', 'Denver', '+13033992560', '(303) 399-2560'], ['Wrbu8rpUiy63RL4slvJCAw', 'Xiquita', False, 107, 'Mexican', 4.4, 39.746002, -104.980866, 'No', 'No', 'No', None, 'Denver', '+17202872701', '(720) 287-2701'], ['Y8Np2emyG1l8yyg3jWovAQ', "Jovanina's Broken Italian", False, 530, 'Italian', 4.2, 39.7498466483866, -104.99979224056, 'yes', 'No', 'yes', None, 'Denver', '+17205417721', '(720) 541-7721'], ['9aZRlwqxx0r709kgOGeCcw', 'Uncle', False, 393, 'Ramen', 4.3, 39.71497, -104.98159, 'yes', 'No', 'No', '$$', 'Denver', '+17206381859', '(720) 638-1859'], ['E4HzQMzTSWlRjc8_DCnOYg', 'Postino Broadway', False, 578, 'Wine Bars', 4.5, 39.71915275577964, -104.9876915, 'yes', 'No', 'yes', '$$', 'Denver', '+13033517000', '(303) 351-7000'], ['K_LyxTyTfafUytd75mMmMg', 'Ultreia', False, 526, 'Tapas Bars', 4.1, 39.75305, -104.99995, 'yes', 'No', 'yes', '$$$', 'Denver', '+13035341970', '(303) 534-1970'], ['lqNe_QMrAyZLnEr06F9S_w', 'Jax Fish House & Oyster Bar', False, 1280, 'Seafood', 4.3, 39.75212, -104.9985899, 'yes', 'No', 'yes', '$$', 'Denver', '+13032925767', '(303) 292-5767'], ['IbCPSViliNokpqUsMQ_nbg', 'La Chiva', False, 341, 'Colombian', 4.2, 39.6902499514317, -104.98726887404548, 'yes', 'No', 'yes', '$$', 'Denver', '+17203899847', '(720) 389-9847'], ['hVREDpdqoOiJvaRCiyMO1g', 'FiNO', False, 23, 'Wine Bars', 3.7, 39.7404021894973, -104.95201949999999, 'No', 'No', 'No', None, 'Denver', '+13032844545', '(303) 284-4545'], ['guyzZWM2a4qZxQOvMlFBQg', 'Temaki Den', False, 423, 'Sushi Bars', 4.6, 39.768565137064954, -104.9798032932541, 'yes', 'No', 'yes', '$$$$', 'Denver', '+13032000530', '(303) 200-0530'], ['7yYkXMzgL-zIh-xZB6C7Xg', 'Sauvage', False, 12, 'Food Trucks', 4.3, 39.73428343891622, -104.9584449, 'No', 'No', 'No', None, 'Denver', '+13182720015', '(318) 272-0015'], ['3IHkyNrJfm_CLZ-qWtsdhQ', 'Nola Jane Restaurant & Bar', False, 274, 'Cajun/Creole', 4.1, 39.74862493988192, -105.00026789, 'yes', 'No', 'yes', '$$', 'Denver', '+17205921942', '(720) 592-1942'], ['pnY1m8aBusUCqgD1rUcLyw', 'Panzano', False, 1321, 'Italian', 4.3, 39.747833, -104.992822, 'yes', 'No', 'yes', '$$$', 'Denver', '+13032963525', '(303) 296-3525'], ['iVq2BYW5u58mGLlrevpbTw', 'Water Grill - Denver', False, 431, 'Seafood', 4.3, 39.75081, -104.99734, 'No', 'No', 'No', '$$$', 'Denver', '+13037275711', '(303) 727-5711'], ['LVF3bhuKZpuy-GQYhzmZsA', 'Riot BBQ', False, 144, 'Barbeque', 4.6, 39.676981, -104.992041, 'yes', 'No', 'yes', '$$', 'Denver', '+13038726862', '(303) 872-6862'], ['dlGpaDSUdureTrW_oi9gig', 'TOAD Kitchen', False, 2, 'Asian Fusion', 5.0, 39.73917405158296, -104.97558981534218, 'No', 'No', 'No', None, 'Denver', '', ''], ['XluydvQpT75gjiuRSclhcQ', 'The Denver Central Market', False, 692, 'Bakeries', 4.4, 39.75936357492905, -104.98454807433254, 'No', 'No', 'No', '$$', 'Denver', '', ''], ['iM8ijTk7rpzcwGAIm7thwg', 'Gattara', False, 247, 'Italian', 4.1, 39.744387, -104.983221,

In [7]:
#Veamos los keys del diccionario recibido
data.keys()

dict_keys(['businesses', 'total', 'region'])

In [8]:
#El segundo elemento del diccionario indica el total de restaurants existentes en la API
print('En total la base de datos registra %d restaurants'%data['total'])

En total la base de datos registra 4100 restaurants

Creacion del DataFrame

In [9]:
# Se crea en dataframe con la info seleccionada
Columns= ['id','name_business','is_closed','review_count','categories','rating','latitude', 'longitude','delivery', 'restaurant_reservation','pickup','price','city','phone','display_phone']
dt_restaurant_YELP= pd.DataFrame(Complete_list, columns=Columns)
print(dt_restaurant_YELP)

                         id                           name_business  \
0    GmniFxffmpFcbmb5KWIwbA                        Culinary Dropout
1    Y-c9rFdGYXlT-A1ndoCTrg                              Tavernetta
2    UkXP_D2vih-LS5oAaMxRIg                                Madeline
3    lyit8GGKG4AyxO3CrTQErQ                Jack’s Modern Steakhouse
4    2wrS0h8iXFZTr4p0egCLjQ                  West Saloon & Kitchen
5    svJWwW0ilssyqk_UML0mUg                            Work & Class
6    0jTb4q8Ezil_tXkbZf-HRQ                                Rougarou
7    ywFvkNZVJoXUQbZoq7fr1w                                   Rioja
8    i8VF3q7dTszCcigJSMcJzQ                        Angelo’s Taverna
9    iS9j0iSOhRzBBYJdzzuZFQ                              Point Easy
10   jML03gtMkgIFWX9Iium4Xg                                   Safta
11   x0rVT3E__00xg99uGr0tjg                            Happy Camper
12   InKe17J_fpqDBorFxEsUXw                  Ma's Kitchen Next Door
13   gagUrh3806qc5hZ14F0Odw             Denver Biscuit Co. - Colfax
14   fHR1VVGarB17xh56bxbUcg             Revival Denver Public House
15   vFNCul1JCv4yBtTqdoxscQ                                  Olivia
16   XlNLa_kiknuAfm29wXO8KA                           Pig and Tiger
17   YxeTWblmRB3m7egJzgAJCg                                 Pony Up
18   Xksk_U8F756DUVFCz134Tw                       The Wolf's Tailor
19   UxCQdVtMhGSiZrcGJd12Ig                         Alma Fonda Fina
20   LX8nS1dlW7MEZDDEmVcyGw                               Root Down
21   6-MYTEofJo7jmdoTfuVIHA              Nana's Dim Sum & Dumplings
22   h5ohyi4dOsioSsvSj3398A                                 Monarch
23   pFuMzFgNKdEWXi0ckj0ivw                        Corsica Wine Bar
24   0-O-xCaxbO-ftWVEYVrRlg                      Barcelona Wine Bar
25   kRiwvntcXKDPdtpYKcGPhg                                 Onefold
26   6F4_oM9oRzBDc7KeTEtvcw                          Wild Corgi Pub
27   PHs8DL9UUOOehhUtE5b1qw                          Corinne Denver
28   L3uHyn2eMYOur3CRLkg8sA                         Mezcaleria Alma
29   SND7k63zO_UuV-Sr--knpA              Painted RiNo Kitchen + Bar
30   KeRN5k0IFBEdGhDTRNZe_g                     The Porchetta House
31   EjNI-dNAMrYxKgUIkqeqhg       Guard and Grace Modern Steakhouse
32   QWWfOQ9yrWDuZwP-mgL1Ig                     Lucina Eatery & Bar
33   rdZPV9r3WPlke0ZO1mRcNA                          Pete's Kitchen
34   R5sNCLBmMp61uYui1Wp5UA                    Toki Ramen And Sushi
35   LLxpJh4yyExw1K7GJsB2zw                           A5 Steakhouse
36   43DCpM0VKoFY-Mnv30RhLQ                                    Kyuu
37   c3QuHjgIkESyn_eD4EiACA                                Nocturne
38   -mLKEN6U1vmBs8IxxBVaEw                             Fish N Beer
39   FIabjV94L_-HH9w8rT6j3Q           Carne - Argentina Street Food
40   qwklKpOZFgOOjMm3-NMzNA                                BurnDown
41   NOkJ14ltntgE4XWS5AgOSA                       The Brutal Poodle
42   7A70YVFJBWN6fbCYQPpNIA                       Brasserie Brixton
43   Lu6Uk12Rg0jkUQUzcHLWFw                         Fox And The Hen
44   s87TW7XplzOqu66TxIyw3g                           Margot Denver
45   GxCgbV8rB7ORs8g0J2nMwQ                         Noodles By Nina
46   MYs1Jc9wj3EjrL5TxR7x-g                     Gabys German Eatery
47   X3_hbxeKNXChhvnAF7RnRQ                         30Forth Kitchen
48   ewCTNd0cUPMY32kD5opphw   Chubby Cattle Hotpot & Sushi - Denver
49   CQNv4SXqFltcwNsx-qHbLQ                        Steuben's Uptown
50   jVOAZe9L3Kwx9Ze-UhT3_w              Odyssey Italian Restaurant
51   zN55MOWDOYAUhJHRVBx9EA                         Paperboy Denver
52   JJiugrBcZrNpX0ueUBuvrg           Cherry Cricket - Cherry Creek
53   k1mGLPBSaUhZKem1KrXLJQ                     Stout Street Social
54   ZnhMS3NichhkEPUmTqJfbw                             Mantra cafe
55   8wmfcpBTOn6BwC1YPvOmDA                                   Rōmyō
56   sU4K-0uTlhvn3OTGqnKamw                                 Heretik
57   yXVJ_K6vdpM3PwfHfkyn5g                              Mister Oso
58   NGiJYiciQao11MXwl-56pg                                 Kawa Ni
59   lSndVTQ9XCpz9fDMFpSBug                              Carne RiNo
60   BHpQiNX5LF79RHTCng8TqQ                      Nola Voodoo Tavern
61   2gGWFWp3DIjxzE3lVFZtNA                             Little Wolf
62   VxSKu6BxKiT1jRr6arsLLg               Cherry Cricket - Downtown
63   DFzFzU6iHbXZtTGu1mN4IA                             Stellar Jay
64   tnFs9EImexnBdlwZjmEfcw                           Horse & Tiger
65   viYTcIvA2l_iSqrNpWeTdA  Yahya's Mediterranean Grill & Pastries
66   s0_kPOB-ywdGUMdqHw5uTg                         Dearly Departed
67   6VE5QY2ULcc8JHB-eLARag                                  Alteño
68   _fcKVnAc2n2Nj5vX-vcLAA                                Aguanile
69   u0lEXYd_cdf2_Zg99rSM9w               Vine Street Pub & Brewery
70   fdipNvAALQxjJWNz-USidQ                    Hillstone Restaurant
71   biju9F9GKy0Ogn3YotSZ4A                              Wildflower
72   O2DoP-SUVov0qwAn1atMbg                         Champagne Tiger
73   swPiklhuXaMLnw5Rh2y7Ew                              Rhein Haus
74   gGXnG-Rf5UUr6wT8krXT5w                       Williams & Graham
75   m3ifi6O7ntMta8102eVgow                             Uchi Denver
76   IHS_gAK8AEYKqs6RCQXSEw                    Florence Supper Club
77   OGwS_BIkHSWdcvQRdW_kfA                    Four Friends Kitchen
78   JRNo_7YSPyVBTMNpu8ZkLA                       The Velvet Cellar
79   Z8vO_mf1V09QDUPdyqJ6og                                  Linger
80   6fJltLxQcLgO0owitrzlBQ                    Cuba Cuba Cafe & Bar
81   pm-Rc3kcCuT5RGbNIldinA                                   Acova
82   uQd0TZKBprBXxF1aGSIAIA                            Dew Drop Inn
83   T0oDpWqZWOjli02HuIO3DQ                                 Potager
84   kI5oOBAGS-Vo4chwmgOVmQ                             Cart-Driver
85   nMagfV2RQrH0N0EZ46AHRg                                  Cimera
86   _2vT7PH78NIqleshrnb19w                                   Brutø
87   KwmKhdWpcIzypdjAUNrc7w                              Mercantile
88   PUhHWM8_rbwUD-8gzfCSOg                                 Sắp Sửa
89   WTe8uL6vF1ZuKAeJIvxR8w                                Savina's
90   QZAZrHljjy8qh1QXacT0tg                           Olive & Finch
91   XWqdMrdt8OJWT6ECMvavPw                             The Plimoth
92   HlL84_OVXvKHndkCqQJn2w                        Kkoki Korean BBQ
93   wL04ets5vd2CGxbzj3ii5w                        Blue Agave Grill
94   46gG3_h3zwFfkf4_183Ydg                         Somebody People
95   izi7Hh5Kz7iC4gEjQ4BxSw                             Dear Emilia
96   zvxXmGRW464sEe-8TVrPGQ                                 Ni Tuyo
97   bb_VNwJQLzao_3HSGx6B9g                             Postino 9CO
98   5lCzYPnAoNNlAZxW3rr_RA                        Satchel's on 6th
99   Wrbu8rpUiy63RL4slvJCAw                                 Xiquita
100  Y8Np2emyG1l8yyg3jWovAQ               Jovanina's Broken Italian
101  9aZRlwqxx0r709kgOGeCcw                                   Uncle
102  E4HzQMzTSWlRjc8_DCnOYg                        Postino Broadway
103  K_LyxTyTfafUytd75mMmMg                                 Ultreia
104  lqNe_QMrAyZLnEr06F9S_w             Jax Fish House & Oyster Bar
105  IbCPSViliNokpqUsMQ_nbg                                La Chiva
106  hVREDpdqoOiJvaRCiyMO1g                                    FiNO
107  guyzZWM2a4qZxQOvMlFBQg                              Temaki Den
108  7yYkXMzgL-zIh-xZB6C7Xg                                 Sauvage
109  3IHkyNrJfm_CLZ-qWtsdhQ              Nola Jane Restaurant & Bar
110  pnY1m8aBusUCqgD1rUcLyw                                 Panzano
111  iVq2BYW5u58mGLlrevpbTw                    Water Grill - Denver
112  LVF3bhuKZpuy-GQYhzmZsA                                Riot BBQ
113  dlGpaDSUdureTrW_oi9gig                            TOAD Kitchen
114  XluydvQpT75gjiuRSclhcQ               The Denver Central Market
115  iM8ijTk7rpzcwGAIm7thwg                                 Gattara
116  MvS8MEgkEvhA9mv-y5Wtow                                 Dio Mio
117  SP58V3g_vD92c7Njh6NLiw                      Apres Govnr's Park
118  IqC4v53GgZce6TbLqyFa7Q                             Bull & Bush
119  FBqPcIryM6R-k1KV7WLwOw                              Death & Co
120  QAMR-ujpiN4nuggIDMBXaA                              Difranco’s
121  fdeVBWzB4jZV7QupbQSXUg                     Urban Farmer Denver
122  EOh9f0jI92sZZa76QLKb-g                                  Beckon
123  Ttk8uzixI-qX8LhdHINV9A                                    Toro
124  jx5kzkP_9zwh9BW0WVPAWw                           Osteria Marco
125  kDFzP_99yO-iQZRDfHJ30Q                               The Crypt
126  kfTdkvBUiAqqzISm_cq23A                               Hop Alley
127  0718djzuQihUiWsjriPjZg                                  Velada
128  HRBLmk4cyiwaIGuZRPEGBg             Woodie Fisher Kitchen & Bar
129  PIg2YoMC44y-K8IT0-vkdw                             Yuan Wonton
130  n18mJPI6mQfBJEp8UrITyw                          Blue Pan Pizza
131  73GqioIw-vz3oNmb-g9Kew                               Major Tom
132  AVfpz6GAPKx659IujpCFbQ                         Odie B's - Rino
133  N_tX1pJz92Ls-4sMQvMLpA                            Postino LoHi
134  NwkErPU8Y7bgmndQSbVGqA                              Chez Maggy
135  yStfRVi_w8jxIjRExfviEA                                 El Five
136  NkjpBZfR4455T7uWvtRN-w                           Bao Brewhouse
137  ENDOWXUYlg_EBwvflvlXLQ                           Kealoha's BBQ
138  psESMQAg6u2MNnY5DzGcDQ                         Appaloosa Grill
139  jsra5k3lfG98mskRwpIwKQ           Teachers' Lounge Food + Drink
140  wPF66bLia0g1hBVRQTNNWQ                             Urban Burma
141  9ZA3ixRK1v0pu_RCo-XGmw         Tamayo by Chef Richard Sandoval
142  KirNvv8CPBgcX_Bd0X56gQ                    Lo Stella Ristorante
143  lpiXtr3y25zPlnS6VFFa7Q                        Stowaway Kitchen
144  SPX2s5yt1jam4Jd1niyX7A                               Bastien's
145  blN3TMM-RMh5Oxo6hyovjA                                La Forêt
146  6ThdJligZWCUCKjnbKgKFQ                         Quality Italian
147  5G2X2q9p7QFdm-LbyutltQ                                   Jelly
148  JYNBJR0dnOUAqbaSxPNqMQ                                 La Loma
149  7cHFgxf33rmfGavv4fOU1A                              Dos Santos
150  krTukO9cN3qzN5oHSU1Klw                              Bombshells
151  K2fzLQ4DjVQvwYRokP4kDA                       Park Avenue Tacos
152  QgLBYDNHkj7Ju0Pcy7Tp5Q                        Trattoria Stella
153  FU8WEWX_wC9z7ol0zblmJg                         British Bulldog
154  alVuEHMqyyTpXZKcIfKT9w                               White Pie
155  ou6C-9GdnDiwMTnrjPZnsw               Insee Father Noodle House
156  u2lZ_RdX4eDbiq61oPmy1Q                            Chicken Riot
157  8yhPR4y5LdzaO3BFnz-psw           Kallisto Modern Mediterranean
158  3u4kl7SbPsSyivTa65LHvA                           Bourbon Grill
159  5OFnTGtVx4lfzcS7HcEaFQ                                  MAKfam
160  _nAgQgTcV2YslQyUSmnw8Q                                 Annette
161  7UWt_282vPsGQPtrquRR9Q                        Shells and Sauce
162  9jlTFXa3Pcr14BneTHCtyw                           Colorado Sake
163  EbWF_4FyGbwhpOwK_Z-hrw                Wally's Wisconsin Tavern
164  hdJntbVh6kDDFR96GpBsVA          Molotov Kitschen and Cocktails
165  3ncWfQJg_RbTqnkPmksoAA                              Sam's No 3
166  uAsOPByhA_JiDi1d8K7cjw                         5280 Burger Bar
167  KO2_h-cW-V_pfauC5aaRTQ                      Cherry Creek Grill
168  27Ev4IchdObRnIuojRfwOA                        The Kentucky Inn
169  Zw0InqIH5vq4qHLRlxnabA              Ma’s Kitchen Dim Sum & Bar
170  Z7nazPnqUFxxdsgDIYNbng                              Yard House
171  cnzv2CYC7gbtwKarP9uajg                       The Flaming Grill
172  w1yt-6MUeY3UrgwH4UUuJQ                                   Gyroz
173  bug5m_Ffzvt42Sr3UkvNjQ                  Atomic Cowboy - Colfax
174  Jfj_tln71utwjuEFLQBl4g                                 Bar Nun
175  ErdOOovTcfW8sOjtKKSHmw                      Butcher Block Cafe
176  _molEkxuooEgIbSDWZdi1Q                               Broderick
177  yuePQBmo1Dn65HhDRfmV0Q            Picaera Puerto Rican Cuisine
178  lSR3JxlJCre6tK31YMmiYw                                  Kizaki
179  jnGNzC_OBlRxjljSJTLDTA        Federales Tacos & Tequila - RiNo
180  MI5j0tRZoW-yBBh7Le0k7g                            EatingPrimal
181  ofPa6i98oFCiq0zoWj1cvw                     Black Shirt Brewing
182  VzermHw6lXFWnpTklIItbQ                       Post Oak Barbecue
183  XwOOlFxQSFyTY0xdM-tUfQ                         Tom's Watch Bar
184  Gl-U2U-pA5Ce1b8zlvXmCA                               Hey Kiddo
185  ZVRZablopgmiT7Z04DJAeA                             Cafe Miriam
186  e8owGfi2rgiPTG6yaDvEqg                       Salt Water Social
187  ziS-GJn-3Ux6t5l-0IUNog                      The Capital Grille
188  gSDlApOoOhOpM1GeqSLtow                    Gaia Masala & Burger
189  gXdK2f4ysEZfHeVMZm_oQg                    Gaia Masala & Burger
190  qMc717YSPhV7Tq4OReKiBQ                           Tatsu Izakaya
191  my9qlzlenBMbAgTiTwvA5w               Crave Mediterranean Grill
192  J9db340h8kR3-A1iiYIluw                           Dragon Cactus
193  hjAhGC7wEb-0l-BbA-MS3g                         King Dumpling 2
194  O0naNbBI7QmrJrCS5u7vYA                                 Benzina
195  N8S43Z8qdJSyqAOcHcsvFA                       Neko Ramen & Rice
196  ns_4vIbSidCY4IZxQ3odfw                  Crazy Mountain Taproom
197  MVLOmqZiIxjsEcx7IjaFPw         JINYA Ramen Bar - Union Station
198  jBYiqfBCJf6r2JbD-GPa7Q                  Chubby Unicorn Cantina
199  e1bAJ7DIYL953AsMer9Q-g                              Yacht Club

     is_closed  review_count              categories  rating   latitude  \
0        False          1038            New American     4.2  39.731320
1        False           990                 Italian     4.5  39.753023
2        False            20             Restaurants     4.9  39.725727
3        False           252                    Bars     4.6  39.689850
4        False          1098                American     4.5  39.744030
5        False          1893            New American     4.5  39.757610
6        False            59                Southern     4.7  39.756240
7        False          2930            New American     4.3  39.747808
8        False          2033                 Italian     4.4  39.725523
9        False            94            New American     4.6  39.756880
10       False          1089          Middle Eastern     4.4  39.768936
11       False          1232                   Pizza     4.2  39.762230
12       False            78               Pan Asian     4.7  39.740336
13       False          4998              Sandwiches     4.5  39.740340
14       False           247           Cocktail Bars     4.1  39.743119
15       False           310                 Italian     4.6  39.711269
16       False            65               Taiwanese     4.4  39.750820
17       False           480              Sandwiches     4.5  39.752420
18       False           337            New American     4.4  39.772770
19       False           308                 Mexican     4.7  39.758115
20       False          4192            New American     4.4  39.763060
21       False           645                 Dim Sum     4.5  39.763536
22       False             8                   Pizza     5.0  39.743040
23       False           261               Wine Bars     4.3  39.761415
24       False          1269      Tapas/Small Plates     4.3  39.761334
25       False          1245      Breakfast & Brunch     4.3  39.744660
26       False           149                    Pubs     4.3  39.736970
27       False           766      Breakfast & Brunch     4.0  39.744068
28       False           117               Wine Bars     4.8  39.758050
29       False            10      Breakfast & Brunch     4.3  39.771660
30       False           165              Sandwiches     4.7  39.740399
31       False          2135             Steakhouses     4.5  39.747956
32       False           170          Latin American     4.6  39.750170
33       False           971                   Greek     3.9  39.739781
34       False            35                   Ramen     4.9  39.691413
35       False           321             Steakhouses     4.3  39.750279
36       False            14                Japanese     4.8  39.743054
37       False           429            Jazz & Blues     4.6  39.759590
38       False           528                 Seafood     4.6  39.767199
39       False           116              Sandwiches     4.7  39.720498
40       False           228                    Bars     4.1  39.708036
41       False           624                    Bars     4.5  39.680880
42       False           165                  French     4.4  39.768309
43       False           429      Breakfast & Brunch     4.4  39.762136
44       False            58            New American     4.7  39.688441
45       False           145                 Noodles     4.5  39.742908
46       False           138                  German     4.5  39.712410
47       False             6            New American     5.0  39.758766
48       False          1681                 Hot Pot     4.2  39.716748
49       False          3476                  Diners     4.0  39.743490
50       False          1536                Sicilian     4.3  39.725781
51       False            72      Breakfast & Brunch     4.3  39.762003
52       False          3535                 Burgers     4.0  39.719634
53       False          1747            New American     4.0  39.744288
54       False            72                  Indian     4.6  39.734877
55       False            28                 Italian     4.3  39.747612
56       False            23                 Spanish     4.7  39.759704
57       False           501                   Tacos     4.1  39.764240
58       False           254                 Izakaya     4.5  39.761783
59       False           113             Steakhouses     4.4  39.758800
60       False           332                   Cafes     4.5  39.764695
61       False            50            Whiskey Bars     4.8  39.777090
62       False           535             Sports Bars     4.1  39.756308
63       False            72             Restaurants     4.3  39.740315
64       False             9            Comfort Food     5.0  39.778458
65       False           683           Mediterranean     4.6  39.740169
66       False            14           Cocktail Bars     4.9  39.759241
67       False           100                 Mexican     4.5  39.720399
68       False            14            Puerto Rican     4.6  39.708693
69       False          1003                American     4.2  39.743400
70       False           780            New American     3.7  39.721141
71       False           231           Cocktail Bars     4.6  39.767589
72       False            79                  French     4.5  39.740206
73       False           622                    Bars     3.7  39.748355
74       False          1136                American     4.4  39.761950
75       False          1140                Japanese     4.5  39.756926
76       False            58                 Italian     4.2  39.709730
77       False          2217                Southern     4.3  39.757478
78       False           118           Cocktail Bars     4.4  39.750965
79       False          4438            Asian Fusion     4.1  39.759540
80       False          1033                   Cuban     4.4  39.735085
81       False           736            New American     4.3  39.767777
82       False            89              Gastropubs     4.5  39.743400
83       False           500            New American     3.8  39.733960
84       False           830                   Pizza     4.5  39.757530
85       False            71          Latin American     3.7  39.768434

Verificación de datos

In [10]:
#Revisión de información general del dataFrame
dt_restaurant_YELP.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      200 non-null    str
 1   name_business           200 non-null    str
 2   is_closed               200 non-null    bool
 3   review_count            200 non-null    int64
 4   categories              200 non-null    str
 5   rating                  200 non-null    float64
 6   latitude                200 non-null    float64
 7   longitude               200 non-null    float64
 8   delivery                200 non-null    str
 9   restaurant_reservation  200 non-null    str
 10  pickup                  200 non-null    str
 11  price                   127 non-null    str
 12  city                    200 non-null    str
 13  phone                   200 non-null    str
 14  display_phone           200 non-null    str
dtypes: bool(1), float64(3), int64(1), str(10)
memory usage: 38.9 KB

Eliminacion de duplicados

In [11]:
#Se verifica locales duplicados a través del id y se verifica con Data Wrangler que sean unicos verificando que los valores de latitud y longitus sean diferentes
Duplicated_Rows=dt_restaurant_YELP[dt_restaurant_YELP.duplicated(subset=['id'])]
print(Duplicated_Rows)

Empty DataFrame
Columns: [id, name_business, is_closed, review_count, categories, rating, latitude, longitude, delivery, restaurant_reservation, pickup, price, city, phone, display_phone]
Index: []

Limpieza de datos

In [12]:
#Revision general de posibles datos atípicos
dt_restaurant_YELP.describe()
#No se encuentran anomalías

       review_count      rating    latitude   longitude
count    200.000000  200.000000  200.000000  200.000000
mean     603.385000    4.338500   39.743100 -104.980427
std      813.444365    0.310726    0.021372    0.024719
min        1.000000    3.400000   39.676981 -105.063120
25%       93.250000    4.100000   39.735205 -104.996371
50%      331.500000    4.400000   39.745705 -104.982462
75%      766.750000    4.500000   39.758118 -104.969122
max     4998.000000    5.000000   39.778458 -104.870020

Estandarización de texto str

In [13]:
# Se seleccionan las columnas tipo Str
Columns_Text = dt_restaurant_YELP.select_dtypes(include=[str]).columns
Col_tex=Columns_Text.drop(['id','price','phone','display_phone'])
print(Col_tex)

#Se normalizan las columnas tipo str todas a minusculas y con un soloo
for col in Col_tex:
    dt_restaurant_YELP[col]=dt_restaurant_YELP[col].astype(str).str.strip().str.lower()
    print(dt_restaurant_YELP)

Index(['name_business', 'categories', 'delivery', 'restaurant_reservation',
       'pickup', 'city'],
      dtype='str')

                         id                           name_business  \
0    GmniFxffmpFcbmb5KWIwbA                        culinary dropout
1    Y-c9rFdGYXlT-A1ndoCTrg                              tavernetta
2    UkXP_D2vih-LS5oAaMxRIg                                madeline
3    lyit8GGKG4AyxO3CrTQErQ                jack’s modern steakhouse
4    2wrS0h8iXFZTr4p0egCLjQ                   west saloon & kitchen
5    svJWwW0ilssyqk_UML0mUg                            work & class
6    0jTb4q8Ezil_tXkbZf-HRQ                                rougarou
7    ywFvkNZVJoXUQbZoq7fr1w                                   rioja
8    i8VF3q7dTszCcigJSMcJzQ                        angelo’s taverna
9    iS9j0iSOhRzBBYJdzzuZFQ                              point easy
10   jML03gtMkgIFWX9Iium4Xg                                   safta
11   x0rVT3E__00xg99uGr0tjg                            happy camper
12   InKe17J_fpqDBorFxEsUXw                  ma's kitchen next door
13   gagUrh3806qc5hZ14F0Odw             denver biscuit co. - colfax
14   fHR1VVGarB17xh56bxbUcg             revival denver public house
15   vFNCul1JCv4yBtTqdoxscQ                                  olivia
16   XlNLa_kiknuAfm29wXO8KA                           pig and tiger
17   YxeTWblmRB3m7egJzgAJCg                                 pony up
18   Xksk_U8F756DUVFCz134Tw                       the wolf's tailor
19   UxCQdVtMhGSiZrcGJd12Ig                         alma fonda fina
20   LX8nS1dlW7MEZDDEmVcyGw                               root down
21   6-MYTEofJo7jmdoTfuVIHA              nana's dim sum & dumplings
22   h5ohyi4dOsioSsvSj3398A                                 monarch
23   pFuMzFgNKdEWXi0ckj0ivw                        corsica wine bar
24   0-O-xCaxbO-ftWVEYVrRlg                      barcelona wine bar
25   kRiwvntcXKDPdtpYKcGPhg                                 onefold
26   6F4_oM9oRzBDc7KeTEtvcw                          wild corgi pub
27   PHs8DL9UUOOehhUtE5b1qw                          corinne denver
28   L3uHyn2eMYOur3CRLkg8sA                         mezcaleria alma
29   SND7k63zO_UuV-Sr--knpA              painted rino kitchen + bar
30   KeRN5k0IFBEdGhDTRNZe_g                     the porchetta house
31   EjNI-dNAMrYxKgUIkqeqhg       guard and grace modern steakhouse
32   QWWfOQ9yrWDuZwP-mgL1Ig                     lucina eatery & bar
33   rdZPV9r3WPlke0ZO1mRcNA                          pete's kitchen
34   R5sNCLBmMp61uYui1Wp5UA                    toki ramen and sushi
35   LLxpJh4yyExw1K7GJsB2zw                           a5 steakhouse
36   43DCpM0VKoFY-Mnv30RhLQ                                    kyuu
37   c3QuHjgIkESyn_eD4EiACA                                nocturne
38   -mLKEN6U1vmBs8IxxBVaEw                             fish n beer
39   FIabjV94L_-HH9w8rT6j3Q           carne - argentina street food
40   qwklKpOZFgOOjMm3-NMzNA                                burndown
41   NOkJ14ltntgE4XWS5AgOSA                       the brutal poodle
42   7A70YVFJBWN6fbCYQPpNIA                       brasserie brixton
43   Lu6Uk12Rg0jkUQUzcHLWFw                         fox and the hen
44   s87TW7XplzOqu66TxIyw3g                           margot denver
45   GxCgbV8rB7ORs8g0J2nMwQ                         noodles by nina
46   MYs1Jc9wj3EjrL5TxR7x-g                     gabys german eatery
47   X3_hbxeKNXChhvnAF7RnRQ                         30forth kitchen
48   ewCTNd0cUPMY32kD5opphw   chubby cattle hotpot & sushi - denver
49   CQNv4SXqFltcwNsx-qHbLQ                        steuben's uptown
50   jVOAZe9L3Kwx9Ze-UhT3_w              odyssey italian restaurant
51   zN55MOWDOYAUhJHRVBx9EA                         paperboy denver
52   JJiugrBcZrNpX0ueUBuvrg           cherry cricket - cherry creek
53   k1mGLPBSaUhZKem1KrXLJQ                     stout street social
54   ZnhMS3NichhkEPUmTqJfbw                             mantra cafe
55   8wmfcpBTOn6BwC1YPvOmDA                                   rōmyō
56   sU4K-0uTlhvn3OTGqnKamw                                 heretik
57   yXVJ_K6vdpM3PwfHfkyn5g                              mister oso
58   NGiJYiciQao11MXwl-56pg                                 kawa ni
59   lSndVTQ9XCpz9fDMFpSBug                              carne rino
60   BHpQiNX5LF79RHTCng8TqQ                      nola voodoo tavern
61   2gGWFWp3DIjxzE3lVFZtNA                             little wolf
62   VxSKu6BxKiT1jRr6arsLLg               cherry cricket - downtown
63   DFzFzU6iHbXZtTGu1mN4IA                             stellar jay
64   tnFs9EImexnBdlwZjmEfcw                           horse & tiger
65   viYTcIvA2l_iSqrNpWeTdA  yahya's mediterranean grill & pastries
66   s0_kPOB-ywdGUMdqHw5uTg                         dearly departed
67   6VE5QY2ULcc8JHB-eLARag                                  alteño
68   _fcKVnAc2n2Nj5vX-vcLAA                                aguanile
69   u0lEXYd_cdf2_Zg99rSM9w               vine street pub & brewery
70   fdipNvAALQxjJWNz-USidQ                    hillstone restaurant
71   biju9F9GKy0Ogn3YotSZ4A                              wildflower
72   O2DoP-SUVov0qwAn1atMbg                         champagne tiger
73   swPiklhuXaMLnw5Rh2y7Ew                              rhein haus
74   gGXnG-Rf5UUr6wT8krXT5w                       williams & graham
75   m3ifi6O7ntMta8102eVgow                             uchi denver
76   IHS_gAK8AEYKqs6RCQXSEw                    florence supper club
77   OGwS_BIkHSWdcvQRdW_kfA                    four friends kitchen
78   JRNo_7YSPyVBTMNpu8ZkLA                       the velvet cellar
79   Z8vO_mf1V09QDUPdyqJ6og                                  linger
80   6fJltLxQcLgO0owitrzlBQ                    cuba cuba cafe & bar
81   pm-Rc3kcCuT5RGbNIldinA                                   acova
82   uQd0TZKBprBXxF1aGSIAIA                            dew drop inn
83   T0oDpWqZWOjli02HuIO3DQ                                 potager
84   kI5oOBAGS-Vo4chwmgOVmQ                             cart-driver
85   nMagfV2RQrH0N0EZ46AHRg                                  cimera
86   _2vT7PH78NIqleshrnb19w                                   brutø
87   KwmKhdWpcIzypdjAUNrc7w                              mercantile
88   PUhHWM8_rbwUD-8gzfCSOg                                 sắp sửa
89   WTe8uL6vF1ZuKAeJIvxR8w                                savina's
90   QZAZrHljjy8qh1QXacT0tg                           olive & finch
91   XWqdMrdt8OJWT6ECMvavPw                             the plimoth
92   HlL84_OVXvKHndkCqQJn2w                        kkoki korean bbq
93   wL04ets5vd2CGxbzj3ii5w                        blue agave grill
94   46gG3_h3zwFfkf4_183Ydg                         somebody people
95   izi7Hh5Kz7iC4gEjQ4BxSw                             dear emilia
96   zvxXmGRW464sEe-8TVrPGQ                                 ni tuyo
97   bb_VNwJQLzao_3HSGx6B9g                             postino 9co
98   5lCzYPnAoNNlAZxW3rr_RA                        satchel's on 6th
99   Wrbu8rpUiy63RL4slvJCAw                                 xiquita
100  Y8Np2emyG1l8yyg3jWovAQ               jovanina's broken italian
101  9aZRlwqxx0r709kgOGeCcw                                   uncle
102  E4HzQMzTSWlRjc8_DCnOYg                        postino broadway
103  K_LyxTyTfafUytd75mMmMg                                 ultreia
104  lqNe_QMrAyZLnEr06F9S_w             jax fish house & oyster bar
105  IbCPSViliNokpqUsMQ_nbg                                la chiva
106  hVREDpdqoOiJvaRCiyMO1g                                    fino
107  guyzZWM2a4qZxQOvMlFBQg                              temaki den
108  7yYkXMzgL-zIh-xZB6C7Xg                                 sauvage
109  3IHkyNrJfm_CLZ-qWtsdhQ              nola jane restaurant & bar
110  pnY1m8aBusUCqgD1rUcLyw                                 panzano
111  iVq2BYW5u58mGLlrevpbTw                    water grill - denver
112  LVF3bhuKZpuy-GQYhzmZsA                                riot bbq
113  dlGpaDSUdureTrW_oi9gig                            toad kitchen
114  XluydvQpT75gjiuRSclhcQ               the denver central market
115  iM8ijTk7rpzcwGAIm7thwg                                 gattara
116  MvS8MEgkEvhA9mv-y5Wtow                                 dio mio
117  SP58V3g_vD92c7Njh6NLiw                      apres govnr's park
118  IqC4v53GgZce6TbLqyFa7Q                             bull & bush
119  FBqPcIryM6R-k1KV7WLwOw                              death & co
120  QAMR-ujpiN4nuggIDMBXaA                              difranco’s
121  fdeVBWzB4jZV7QupbQSXUg                     urban farmer denver
122  EOh9f0jI92sZZa76QLKb-g                                  beckon
123  Ttk8uzixI-qX8LhdHINV9A                                    toro
124  jx5kzkP_9zwh9BW0WVPAWw                           osteria marco
125  kDFzP_99yO-iQZRDfHJ30Q                               the crypt
126  kfTdkvBUiAqqzISm_cq23A                               hop alley
127  0718djzuQihUiWsjriPjZg                                  velada
128  HRBLmk4cyiwaIGuZRPEGBg             woodie fisher kitchen & bar
129  PIg2YoMC44y-K8IT0-vkdw                             yuan wonton
130  n18mJPI6mQfBJEp8UrITyw                          blue pan pizza
131  73GqioIw-vz3oNmb-g9Kew                               major tom
132  AVfpz6GAPKx659IujpCFbQ                         odie b's - rino
133  N_tX1pJz92Ls-4sMQvMLpA                            postino lohi
134  NwkErPU8Y7bgmndQSbVGqA                              chez maggy
135  yStfRVi_w8jxIjRExfviEA                                 el five
136  NkjpBZfR4455T7uWvtRN-w                           bao brewhouse
137  ENDOWXUYlg_EBwvflvlXLQ                           kealoha's bbq
138  psESMQAg6u2MNnY5DzGcDQ                         appaloosa grill
139  jsra5k3lfG98mskRwpIwKQ           teachers' lounge food + drink
140  wPF66bLia0g1hBVRQTNNWQ                             urban burma
141  9ZA3ixRK1v0pu_RCo-XGmw         tamayo by chef richard sandoval
142  KirNvv8CPBgcX_Bd0X56gQ                    lo stella ristorante
143  lpiXtr3y25zPlnS6VFFa7Q                        stowaway kitchen
144  SPX2s5yt1jam4Jd1niyX7A                               bastien's
145  blN3TMM-RMh5Oxo6hyovjA                                la forêt
146  6ThdJligZWCUCKjnbKgKFQ                         quality italian
147  5G2X2q9p7QFdm-LbyutltQ                                   jelly
148  JYNBJR0dnOUAqbaSxPNqMQ                                 la loma
149  7cHFgxf33rmfGavv4fOU1A                              dos santos
150  krTukO9cN3qzN5oHSU1Klw                              bombshells
151  K2fzLQ4DjVQvwYRokP4kDA                       park avenue tacos
152  QgLBYDNHkj7Ju0Pcy7Tp5Q                        trattoria stella
153  FU8WEWX_wC9z7ol0zblmJg                         british bulldog
154  alVuEHMqyyTpXZKcIfKT9w                               white pie
155  ou6C-9GdnDiwMTnrjPZnsw               insee father noodle house
156  u2lZ_RdX4eDbiq61oPmy1Q                            chicken riot
157  8yhPR4y5LdzaO3BFnz-psw           kallisto modern mediterranean
158  3u4kl7SbPsSyivTa65LHvA                           bourbon grill
159  5OFnTGtVx4lfzcS7HcEaFQ                                  makfam
160  _nAgQgTcV2YslQyUSmnw8Q                                 annette
161  7UWt_282vPsGQPtrquRR9Q                        shells and sauce
162  9jlTFXa3Pcr14BneTHCtyw                           colorado sake
163  EbWF_4FyGbwhpOwK_Z-hrw                wally's wisconsin tavern
164  hdJntbVh6kDDFR96GpBsVA          molotov kitschen and cocktails
165  3ncWfQJg_RbTqnkPmksoAA                              sam's no 3
166  uAsOPByhA_JiDi1d8K7cjw                         5280 burger bar
167  KO2_h-cW-V_pfauC5aaRTQ                      cherry creek grill
168  27Ev4IchdObRnIuojRfwOA                        the kentucky inn
169  Zw0InqIH5vq4qHLRlxnabA              ma’s kitchen dim sum & bar
170  Z7nazPnqUFxxdsgDIYNbng                              yard house
171  cnzv2CYC7gbtwKarP9uajg                       the flaming grill
172  w1yt-6MUeY3UrgwH4UUuJQ                                   gyroz
173  bug5m_Ffzvt42Sr3UkvNjQ                  atomic cowboy - colfax
174  Jfj_tln71utwjuEFLQBl4g                                 bar nun
175  ErdOOovTcfW8sOjtKKSHmw                      butcher block cafe
176  _molEkxuooEgIbSDWZdi1Q                               broderick
177  yuePQBmo1Dn65HhDRfmV0Q            picaera puerto rican cuisine
178  lSR3JxlJCre6tK31YMmiYw                                  kizaki
179  jnGNzC_OBlRxjljSJTLDTA        federales tacos & tequila - rino
180  MI5j0tRZoW-yBBh7Le0k7g                            eatingprimal
181  ofPa6i98oFCiq0zoWj1cvw                     black shirt brewing
182  VzermHw6lXFWnpTklIItbQ                       post oak barbecue
183  XwOOlFxQSFyTY0xdM-tUfQ                         tom's watch bar
184  Gl-U2U-pA5Ce1b8zlvXmCA                               hey kiddo
185  ZVRZablopgmiT7Z04DJAeA                             cafe miriam
186  e8owGfi2rgiPTG6yaDvEqg                       salt water social
187  ziS-GJn-3Ux6t5l-0IUNog                      the capital grille
188  gSDlApOoOhOpM1GeqSLtow                    gaia masala & burger
189  gXdK2f4ysEZfHeVMZm_oQg                    gaia masala & burger
190  qMc717YSPhV7Tq4OReKiBQ                           tatsu izakaya
191  my9qlzlenBMbAgTiTwvA5w               crave mediterranean grill
192  J9db340h8kR3-A1iiYIluw                           dragon cactus
193  hjAhGC7wEb-0l-BbA-MS3g                         king dumpling 2
194  O0naNbBI7QmrJrCS5u7vYA                                 benzina
195  N8S43Z8qdJSyqAOcHcsvFA                       neko ramen & rice
196  ns_4vIbSidCY4IZxQ3odfw                  crazy mountain taproom
197  MVLOmqZiIxjsEcx7IjaFPw         jinya ramen bar - union station
198  jBYiqfBCJf6r2JbD-GPa7Q                  chubby unicorn cantina
199  e1bAJ7DIYL953AsMer9Q-g                              yacht club

     is_closed  review_count              categories  rating   latitude  \
0        False          1038            New American     4.2  39.731320
1        False           990                 Italian     4.5  39.753023
2        False            20             Restaurants     4.9  39.725727
3        False           252                    Bars     4.6  39.689850
4        False          1098                American     4.5  39.744030
5        False          1893            New American     4.5  39.757610
6        False            59                Southern     4.7  39.756240
7        False          2930            New American     4.3  39.747808
8        False          2033                 Italian     4.4  39.725523
9        False            94            New American     4.6  39.756880
10       False          1089          Middle Eastern     4.4  39.768936
11       False          1232                   Pizza     4.2  39.762230
12       False            78               Pan Asian     4.7  39.740336
13       False          4998              Sandwiches     4.5  39.740340
14       False           247           Cocktail Bars     4.1  39.743119
15       False           310                 Italian     4.6  39.711269
16       False            65               Taiwanese     4.4  39.750820
17       False           480              Sandwiches     4.5  39.752420
18       False           337            New American     4.4  39.772770
19       False           308                 Mexican     4.7  39.758115
20       False          4192            New American     4.4  39.763060
21       False           645                 Dim Sum     4.5  39.763536
22       False             8                   Pizza     5.0  39.743040
23       False           261               Wine Bars     4.3  39.761415
24       False          1269      Tapas/Small Plates     4.3  39.761334
25       False          1245      Breakfast & Brunch     4.3  39.744660
26       False           149                    Pubs     4.3  39.736970
27       False           766      Breakfast & Brunch     4.0  39.744068
28       False           117               Wine Bars     4.8  39.758050
29       False            10      Breakfast & Brunch     4.3  39.771660
30       False           165              Sandwiches     4.7  39.740399
31       False          2135             Steakhouses     4.5  39.747956
32       False           170          Latin American     4.6  39.750170
33       False           971                   Greek     3.9  39.739781
34       False            35                   Ramen     4.9  39.691413
35       False           321             Steakhouses     4.3  39.750279
36       False            14                Japanese     4.8  39.743054
37       False           429            Jazz & Blues     4.6  39.759590
38       False           528                 Seafood     4.6  39.767199
39       False           116              Sandwiches     4.7  39.720498
40       False           228                    Bars     4.1  39.708036
41       False           624                    Bars     4.5  39.680880
42       False           165                  French     4.4  39.768309
43       False           429      Breakfast & Brunch     4.4  39.762136
44       False            58            New American     4.7  39.688441
45       False           145                 Noodles     4.5  39.742908
46       False           138                  German     4.5  39.712410
47       False             6            New American     5.0  39.758766
48       False          1681                 Hot Pot     4.2  39.716748
49       False          3476                  Diners     4.0  39.743490
50       False          1536                Sicilian     4.3  39.725781
51       False            72      Breakfast & Brunch     4.3  39.762003
52       False          3535                 Burgers     4.0  39.719634
53       False          1747            New American     4.0  39.744288
54       False            72                  Indian     4.6  39.734877
55       False            28                 Italian     4.3  39.747612
56       False            23                 Spanish     4.7  39.759704
57       False           501                   Tacos     4.1  39.764240
58       False           254                 Izakaya     4.5  39.761783
59       False           113             Steakhouses     4.4  39.758800
60       False           332                   Cafes     4.5  39.764695
61       False            50            Whiskey Bars     4.8  39.777090
62       False           535             Sports Bars     4.1  39.756308
63       False            72             Restaurants     4.3  39.740315
64       False             9            Comfort Food     5.0  39.778458
65       False           683           Mediterranean     4.6  39.740169
66       False            14           Cocktail Bars     4.9  39.759241
67       False           100                 Mexican     4.5  39.720399
68       False            14            Puerto Rican     4.6  39.708693
69       False          1003                American     4.2  39.743400
70       False           780            New American     3.7  39.721141
71       False           231           Cocktail Bars     4.6  39.767589
72       False            79                  French     4.5  39.740206
73       False           622                    Bars     3.7  39.748355
74       False          1136                American     4.4  39.761950
75       False          1140                Japanese     4.5  39.756926
76       False            58                 Italian     4.2  39.709730
77       False          2217                Southern     4.3  39.757478
78       False           118           Cocktail Bars     4.4  39.750965
79       False          4438            Asian Fusion     4.1  39.759540
80       False          1033                   Cuban     4.4  39.735085
81       False           736            New American     4.3  39.767777
82       False            89              Gastropubs     4.5  39.743400
83       False           500            New American     3.8  39.733960
84       False           830                   Pizza     4.5  39.757530
85       False            71          Latin American     3.7  39.768434

Eliminar ciudades diferentes a la seleccionada

In [14]:
#Eliminación de información no pprteneciente a Denver
total_no_denver = (dt_restaurant_YELP['city'] != 'denver').sum()
print(total_no_denver)

# Se sobreescribe el dataframe con valores pertencientes solo a Denver
dt_restaurant_YELP= dt_restaurant_YELP[dt_restaurant_YELP['city']== 'denver']
print(dt_restaurant_YELP)

4
                         id                           name_business  \
0    GmniFxffmpFcbmb5KWIwbA                        culinary dropout
1    Y-c9rFdGYXlT-A1ndoCTrg                              tavernetta
2    UkXP_D2vih-LS5oAaMxRIg                                madeline
3    lyit8GGKG4AyxO3CrTQErQ                jack’s modern steakhouse
4    2wrS0h8iXFZTr4p0egCLjQ                   west saloon & kitchen
5    svJWwW0ilssyqk_UML0mUg                            work & class
6    0jTb4q8Ezil_tXkbZf-HRQ                                rougarou
7    ywFvkNZVJoXUQbZoq7fr1w                                   rioja
8    i8VF3q7dTszCcigJSMcJzQ                        angelo’s taverna
9    iS9j0iSOhRzBBYJdzzuZFQ                              point easy
10   jML03gtMkgIFWX9Iium4Xg                                   safta
11   x0rVT3E__00xg99uGr0tjg                            happy camper
12   InKe17J_fpqDBorFxEsUXw                  ma's kitchen next door
13   gagUrh3806qc5hZ14F0Odw             denver biscuit co. - colfax
14   fHR1VVGarB17xh56bxbUcg             revival denver public house
15   vFNCul1JCv4yBtTqdoxscQ                                  olivia
16   XlNLa_kiknuAfm29wXO8KA                           pig and tiger
17   YxeTWblmRB3m7egJzgAJCg                                 pony up
18   Xksk_U8F756DUVFCz134Tw                       the wolf's tailor
19   UxCQdVtMhGSiZrcGJd12Ig                         alma fonda fina
20   LX8nS1dlW7MEZDDEmVcyGw                               root down
21   6-MYTEofJo7jmdoTfuVIHA              nana's dim sum & dumplings
22   h5ohyi4dOsioSsvSj3398A                                 monarch
23   pFuMzFgNKdEWXi0ckj0ivw                        corsica wine bar
24   0-O-xCaxbO-ftWVEYVrRlg                      barcelona wine bar
25   kRiwvntcXKDPdtpYKcGPhg                                 onefold
26   6F4_oM9oRzBDc7KeTEtvcw                          wild corgi pub
27   PHs8DL9UUOOehhUtE5b1qw                          corinne denver
28   L3uHyn2eMYOur3CRLkg8sA                         mezcaleria alma
29   SND7k63zO_UuV-Sr--knpA              painted rino kitchen + bar
30   KeRN5k0IFBEdGhDTRNZe_g                     the porchetta house
31   EjNI-dNAMrYxKgUIkqeqhg       guard and grace modern steakhouse
32   QWWfOQ9yrWDuZwP-mgL1Ig                     lucina eatery & bar
33   rdZPV9r3WPlke0ZO1mRcNA                          pete's kitchen
34   R5sNCLBmMp61uYui1Wp5UA                    toki ramen and sushi
35   LLxpJh4yyExw1K7GJsB2zw                           a5 steakhouse
36   43DCpM0VKoFY-Mnv30RhLQ                                    kyuu
37   c3QuHjgIkESyn_eD4EiACA                                nocturne
38   -mLKEN6U1vmBs8IxxBVaEw                             fish n beer
39   FIabjV94L_-HH9w8rT6j3Q           carne - argentina street food
40   qwklKpOZFgOOjMm3-NMzNA                                burndown
41   NOkJ14ltntgE4XWS5AgOSA                       the brutal poodle
42   7A70YVFJBWN6fbCYQPpNIA                       brasserie brixton
43   Lu6Uk12Rg0jkUQUzcHLWFw                         fox and the hen
44   s87TW7XplzOqu66TxIyw3g                           margot denver
45   GxCgbV8rB7ORs8g0J2nMwQ                         noodles by nina
47   X3_hbxeKNXChhvnAF7RnRQ                         30forth kitchen
48   ewCTNd0cUPMY32kD5opphw   chubby cattle hotpot & sushi - denver
49   CQNv4SXqFltcwNsx-qHbLQ                        steuben's uptown
50   jVOAZe9L3Kwx9Ze-UhT3_w              odyssey italian restaurant
51   zN55MOWDOYAUhJHRVBx9EA                         paperboy denver
52   JJiugrBcZrNpX0ueUBuvrg           cherry cricket - cherry creek
53   k1mGLPBSaUhZKem1KrXLJQ                     stout street social
54   ZnhMS3NichhkEPUmTqJfbw                             mantra cafe
55   8wmfcpBTOn6BwC1YPvOmDA                                   rōmyō
56   sU4K-0uTlhvn3OTGqnKamw                                 heretik
57   yXVJ_K6vdpM3PwfHfkyn5g                              mister oso
58   NGiJYiciQao11MXwl-56pg                                 kawa ni
59   lSndVTQ9XCpz9fDMFpSBug                              carne rino
60   BHpQiNX5LF79RHTCng8TqQ                      nola voodoo tavern
61   2gGWFWp3DIjxzE3lVFZtNA                             little wolf
62   VxSKu6BxKiT1jRr6arsLLg               cherry cricket - downtown
63   DFzFzU6iHbXZtTGu1mN4IA                             stellar jay
64   tnFs9EImexnBdlwZjmEfcw                           horse & tiger
65   viYTcIvA2l_iSqrNpWeTdA  yahya's mediterranean grill & pastries
66   s0_kPOB-ywdGUMdqHw5uTg                         dearly departed
67   6VE5QY2ULcc8JHB-eLARag                                  alteño
68   _fcKVnAc2n2Nj5vX-vcLAA                                aguanile
69   u0lEXYd_cdf2_Zg99rSM9w               vine street pub & brewery
70   fdipNvAALQxjJWNz-USidQ                    hillstone restaurant
71   biju9F9GKy0Ogn3YotSZ4A                              wildflower
72   O2DoP-SUVov0qwAn1atMbg                         champagne tiger
73   swPiklhuXaMLnw5Rh2y7Ew                              rhein haus
74   gGXnG-Rf5UUr6wT8krXT5w                       williams & graham
75   m3ifi6O7ntMta8102eVgow                             uchi denver
76   IHS_gAK8AEYKqs6RCQXSEw                    florence supper club
77   OGwS_BIkHSWdcvQRdW_kfA                    four friends kitchen
78   JRNo_7YSPyVBTMNpu8ZkLA                       the velvet cellar
79   Z8vO_mf1V09QDUPdyqJ6og                                  linger
80   6fJltLxQcLgO0owitrzlBQ                    cuba cuba cafe & bar
81   pm-Rc3kcCuT5RGbNIldinA                                   acova
82   uQd0TZKBprBXxF1aGSIAIA                            dew drop inn
83   T0oDpWqZWOjli02HuIO3DQ                                 potager
84   kI5oOBAGS-Vo4chwmgOVmQ                             cart-driver
85   nMagfV2RQrH0N0EZ46AHRg                                  cimera
86   _2vT7PH78NIqleshrnb19w                                   brutø
87   KwmKhdWpcIzypdjAUNrc7w                              mercantile
88   PUhHWM8_rbwUD-8gzfCSOg                                 sắp sửa
89   WTe8uL6vF1ZuKAeJIvxR8w                                savina's
90   QZAZrHljjy8qh1QXacT0tg                           olive & finch
91   XWqdMrdt8OJWT6ECMvavPw                             the plimoth
92   HlL84_OVXvKHndkCqQJn2w                        kkoki korean bbq
93   wL04ets5vd2CGxbzj3ii5w                        blue agave grill
94   46gG3_h3zwFfkf4_183Ydg                         somebody people
95   izi7Hh5Kz7iC4gEjQ4BxSw                             dear emilia
96   zvxXmGRW464sEe-8TVrPGQ                                 ni tuyo
97   bb_VNwJQLzao_3HSGx6B9g                             postino 9co
98   5lCzYPnAoNNlAZxW3rr_RA                        satchel's on 6th
99   Wrbu8rpUiy63RL4slvJCAw                                 xiquita
100  Y8Np2emyG1l8yyg3jWovAQ               jovanina's broken italian
101  9aZRlwqxx0r709kgOGeCcw                                   uncle
102  E4HzQMzTSWlRjc8_DCnOYg                        postino broadway
103  K_LyxTyTfafUytd75mMmMg                                 ultreia
104  lqNe_QMrAyZLnEr06F9S_w             jax fish house & oyster bar
105  IbCPSViliNokpqUsMQ_nbg                                la chiva
106  hVREDpdqoOiJvaRCiyMO1g                                    fino
107  guyzZWM2a4qZxQOvMlFBQg                              temaki den
108  7yYkXMzgL-zIh-xZB6C7Xg                                 sauvage
109  3IHkyNrJfm_CLZ-qWtsdhQ              nola jane restaurant & bar
110  pnY1m8aBusUCqgD1rUcLyw                                 panzano
111  iVq2BYW5u58mGLlrevpbTw                    water grill - denver
112  LVF3bhuKZpuy-GQYhzmZsA                                riot bbq
113  dlGpaDSUdureTrW_oi9gig                            toad kitchen
114  XluydvQpT75gjiuRSclhcQ               the denver central market
115  iM8ijTk7rpzcwGAIm7thwg                                 gattara
116  MvS8MEgkEvhA9mv-y5Wtow                                 dio mio
117  SP58V3g_vD92c7Njh6NLiw                      apres govnr's park
118  IqC4v53GgZce6TbLqyFa7Q                             bull & bush
119  FBqPcIryM6R-k1KV7WLwOw                              death & co
120  QAMR-ujpiN4nuggIDMBXaA                              difranco’s
121  fdeVBWzB4jZV7QupbQSXUg                     urban farmer denver
122  EOh9f0jI92sZZa76QLKb-g                                  beckon
123  Ttk8uzixI-qX8LhdHINV9A                                    toro
124  jx5kzkP_9zwh9BW0WVPAWw                           osteria marco
125  kDFzP_99yO-iQZRDfHJ30Q                               the crypt
126  kfTdkvBUiAqqzISm_cq23A                               hop alley
127  0718djzuQihUiWsjriPjZg                                  velada
128  HRBLmk4cyiwaIGuZRPEGBg             woodie fisher kitchen & bar
129  PIg2YoMC44y-K8IT0-vkdw                             yuan wonton
130  n18mJPI6mQfBJEp8UrITyw                          blue pan pizza
131  73GqioIw-vz3oNmb-g9Kew                               major tom
132  AVfpz6GAPKx659IujpCFbQ                         odie b's - rino
133  N_tX1pJz92Ls-4sMQvMLpA                            postino lohi
134  NwkErPU8Y7bgmndQSbVGqA                              chez maggy
135  yStfRVi_w8jxIjRExfviEA                                 el five
136  NkjpBZfR4455T7uWvtRN-w                           bao brewhouse
137  ENDOWXUYlg_EBwvflvlXLQ                           kealoha's bbq
138  psESMQAg6u2MNnY5DzGcDQ                         appaloosa grill
139  jsra5k3lfG98mskRwpIwKQ           teachers' lounge food + drink
141  9ZA3ixRK1v0pu_RCo-XGmw         tamayo by chef richard sandoval
142  KirNvv8CPBgcX_Bd0X56gQ                    lo stella ristorante
143  lpiXtr3y25zPlnS6VFFa7Q                        stowaway kitchen
144  SPX2s5yt1jam4Jd1niyX7A                               bastien's
145  blN3TMM-RMh5Oxo6hyovjA                                la forêt
146  6ThdJligZWCUCKjnbKgKFQ                         quality italian
147  5G2X2q9p7QFdm-LbyutltQ                                   jelly
148  JYNBJR0dnOUAqbaSxPNqMQ                                 la loma
149  7cHFgxf33rmfGavv4fOU1A                              dos santos
150  krTukO9cN3qzN5oHSU1Klw                              bombshells
151  K2fzLQ4DjVQvwYRokP4kDA                       park avenue tacos
152  QgLBYDNHkj7Ju0Pcy7Tp5Q                        trattoria stella
153  FU8WEWX_wC9z7ol0zblmJg                         british bulldog
154  alVuEHMqyyTpXZKcIfKT9w                               white pie
155  ou6C-9GdnDiwMTnrjPZnsw               insee father noodle house
156  u2lZ_RdX4eDbiq61oPmy1Q                            chicken riot
157  8yhPR4y5LdzaO3BFnz-psw           kallisto modern mediterranean
158  3u4kl7SbPsSyivTa65LHvA                           bourbon grill
159  5OFnTGtVx4lfzcS7HcEaFQ                                  makfam
161  7UWt_282vPsGQPtrquRR9Q                        shells and sauce
162  9jlTFXa3Pcr14BneTHCtyw                           colorado sake
163  EbWF_4FyGbwhpOwK_Z-hrw                wally's wisconsin tavern
164  hdJntbVh6kDDFR96GpBsVA          molotov kitschen and cocktails
165  3ncWfQJg_RbTqnkPmksoAA                              sam's no 3
166  uAsOPByhA_JiDi1d8K7cjw                         5280 burger bar
167  KO2_h-cW-V_pfauC5aaRTQ                      cherry creek grill
168  27Ev4IchdObRnIuojRfwOA                        the kentucky inn
169  Zw0InqIH5vq4qHLRlxnabA              ma’s kitchen dim sum & bar
170  Z7nazPnqUFxxdsgDIYNbng                              yard house
171  cnzv2CYC7gbtwKarP9uajg                       the flaming grill
172  w1yt-6MUeY3UrgwH4UUuJQ                                   gyroz
173  bug5m_Ffzvt42Sr3UkvNjQ                  atomic cowboy - colfax
174  Jfj_tln71utwjuEFLQBl4g                                 bar nun
175  ErdOOovTcfW8sOjtKKSHmw                      butcher block cafe
176  _molEkxuooEgIbSDWZdi1Q                               broderick
177  yuePQBmo1Dn65HhDRfmV0Q            picaera puerto rican cuisine
178  lSR3JxlJCre6tK31YMmiYw                                  kizaki
179  jnGNzC_OBlRxjljSJTLDTA        federales tacos & tequila - rino
180  MI5j0tRZoW-yBBh7Le0k7g                            eatingprimal
181  ofPa6i98oFCiq0zoWj1cvw                     black shirt brewing
182  VzermHw6lXFWnpTklIItbQ                       post oak barbecue
183  XwOOlFxQSFyTY0xdM-tUfQ                         tom's watch bar
184  Gl-U2U-pA5Ce1b8zlvXmCA                               hey kiddo
185  ZVRZablopgmiT7Z04DJAeA                             cafe miriam
186  e8owGfi2rgiPTG6yaDvEqg                       salt water social
187  ziS-GJn-3Ux6t5l-0IUNog                      the capital grille
188  gSDlApOoOhOpM1GeqSLtow                    gaia masala & burger
189  gXdK2f4ysEZfHeVMZm_oQg                    gaia masala & burger
190  qMc717YSPhV7Tq4OReKiBQ                           tatsu izakaya
192  J9db340h8kR3-A1iiYIluw                           dragon cactus
193  hjAhGC7wEb-0l-BbA-MS3g                         king dumpling 2
194  O0naNbBI7QmrJrCS5u7vYA                                 benzina
195  N8S43Z8qdJSyqAOcHcsvFA                       neko ramen & rice
196  ns_4vIbSidCY4IZxQ3odfw                  crazy mountain taproom
197  MVLOmqZiIxjsEcx7IjaFPw         jinya ramen bar - union station
198  jBYiqfBCJf6r2JbD-GPa7Q                  chubby unicorn cantina
199  e1bAJ7DIYL953AsMer9Q-g                              yacht club

     is_closed  review_count              categories  rating   latitude  \
0        False          1038            new american     4.2  39.731320
1        False           990                 italian     4.5  39.753023
2        False            20             restaurants     4.9  39.725727
3        False           252                    bars     4.6  39.689850
4        False          1098                american     4.5  39.744030
5        False          1893            new american     4.5  39.757610
6        False            59                southern     4.7  39.756240
7        False          2930            new american     4.3  39.747808
8        False          2033                 italian     4.4  39.725523
9        False            94            new american     4.6  39.756880
10       False          1089          middle eastern     4.4  39.768936
11       False          1232                   pizza     4.2  39.762230
12       False            78               pan asian     4.7  39.740336
13       False          4998              sandwiches     4.5  39.740340
14       False           247           cocktail bars     4.1  39.743119
15       False           310                 italian     4.6  39.711269
16       False            65               taiwanese     4.4  39.750820
17       False           480              sandwiches     4.5  39.752420
18       False           337            new american     4.4  39.772770
19       False           308                 mexican     4.7  39.758115
20       False          4192            new american     4.4  39.763060
21       False           645                 dim sum     4.5  39.763536
22       False             8                   pizza     5.0  39.743040
23       False           261               wine bars     4.3  39.761415
24       False          1269      tapas/small plates     4.3  39.761334
25       False          1245      breakfast & brunch     4.3  39.744660
26       False           149                    pubs     4.3  39.736970
27       False           766      breakfast & brunch     4.0  39.744068
28       False           117               wine bars     4.8  39.758050
29       False            10      breakfast & brunch     4.3  39.771660
30       False           165              sandwiches     4.7  39.740399
31       False          2135             steakhouses     4.5  39.747956
32       False           170          latin american     4.6  39.750170
33       False           971                   greek     3.9  39.739781
34       False            35                   ramen     4.9  39.691413
35       False           321             steakhouses     4.3  39.750279
36       False            14                japanese     4.8  39.743054
37       False           429            jazz & blues     4.6  39.759590
38       False           528                 seafood     4.6  39.767199
39       False           116              sandwiches     4.7  39.720498
40       False           228                    bars     4.1  39.708036
41       False           624                    bars     4.5  39.680880
42       False           165                  french     4.4  39.768309
43       False           429      breakfast & brunch     4.4  39.762136
44       False            58            new american     4.7  39.688441
45       False           145                 noodles     4.5  39.742908
47       False             6            new american     5.0  39.758766
48       False          1681                 hot pot     4.2  39.716748
49       False          3476                  diners     4.0  39.743490
50       False          1536                sicilian     4.3  39.725781
51       False            72      breakfast & brunch     4.3  39.762003
52       False          3535                 burgers     4.0  39.719634
53       False          1747            new american     4.0  39.744288
54       False            72                  indian     4.6  39.734877
55       False            28                 italian     4.3  39.747612
56       False            23                 spanish     4.7  39.759704
57       False           501                   tacos     4.1  39.764240
58       False           254                 izakaya     4.5  39.761783
59       False           113             steakhouses     4.4  39.758800
60       False           332                   cafes     4.5  39.764695
61       False            50            whiskey bars     4.8  39.777090
62       False           535             sports bars     4.1  39.756308
63       False            72             restaurants     4.3  39.740315
64       False             9            comfort food     5.0  39.778458
65       False           683           mediterranean     4.6  39.740169
66       False            14           cocktail bars     4.9  39.759241
67       False           100                 mexican     4.5  39.720399
68       False            14            puerto rican     4.6  39.708693
69       False          1003                american     4.2  39.743400
70       False           780            new american     3.7  39.721141
71       False           231           cocktail bars     4.6  39.767589
72       False            79                  french     4.5  39.740206
73       False           622                    bars     3.7  39.748355
74       False          1136                american     4.4  39.761950
75       False          1140                japanese     4.5  39.756926
76       False            58                 italian     4.2  39.709730
77       False          2217                southern     4.3  39.757478
78       False           118           cocktail bars     4.4  39.750965
79       False          4438            asian fusion     4.1  39.759540
80       False          1033                   cuban     4.4  39.735085
81       False           736            new american     4.3  39.767777
82       False            89              gastropubs     4.5  39.743400
83       False           500            new american     3.8  39.733960
84       False           830                   pizza     4.5  39.757530
85       False            71          latin american     3.7  39.768434
86       False           147      tapas/small plates     4.3  39.752781
87       False          1423            new american     4.2  39.753615
88       False           252              vietnamese     4.3  39.739794
89       False          2222                 mexican     4.1  39.744758
90       False           945            new american     4.2  39.743060

In [15]:
dt_restaurant_YELP['phone'] = dt_restaurant_YELP['phone'].replace('', np.nan)
dt_restaurant_YELP['display_phone'] = dt_restaurant_YELP['display_phone'].replace('', np.nan)

Datos nulos

In [16]:
Percentage_Null = dt_restaurant_YELP.isna().mean()*100
print(Percentage_Null)

id                         0.000000
name_business              0.000000
is_closed                  0.000000
review_count               0.000000
categories                 0.000000
rating                     0.000000
latitude                   0.000000
longitude                  0.000000
delivery                   0.000000
restaurant_reservation     0.000000
pickup                     0.000000
price                     36.734694
city                       0.000000
phone                      6.122449
display_phone              6.122449
dtype: float64

In [17]:
#Price se llena con Desconocido, porque queremos al estar escrito en tipo simbolo, evitamos modificar la tendencia
#Ya que faltan un 37% de los datos y usar la moda haría que incurriera en un sesgo grande
dt_restaurant_YELP['price']=dt_restaurant_YELP['price'].fillna('Desconocido')

In [18]:
#Se rellena los valores nulos con 'desconicido' para no inventar informacion falsa
dt_restaurant_YELP['phone']=dt_restaurant_YELP['phone'].fillna('Desconocido')

In [19]:
#Se rellena los valores nulos con 'desconicido' para no inventar informacion falsa
dt_restaurant_YELP['display_phone']=dt_restaurant_YELP['display_phone'].fillna('Desconocido')

In [20]:
Percentage_Null = dt_restaurant_YELP.isna().mean()*100
print(Percentage_Null)

id                        0.0
name_business             0.0
is_closed                 0.0
review_count              0.0
categories                0.0
rating                    0.0
latitude                  0.0
longitude                 0.0
delivery                  0.0
restaurant_reservation    0.0
pickup                    0.0
price                     0.0
city                      0.0
phone                     0.0
display_phone             0.0
dtype: float64

In [21]:
dt_restaurant_YELP

,id,name_business,is_closed,review_count,categories,rating,latitude,longitude,delivery,restaurant_reservation,pickup,price,city,phone,display_phone
0,GmniFxffmpFcbmb5KWIwbA,culinary dropout,False,1038,new american,4.2,39.731320,-104.939180,no,no,no,$$,denver,+17207790190,(720) 779-0190
1,Y-c9rFdGYXlT-A1ndoCTrg,tavernetta,False,990,italian,4.5,39.753023,-105.001968,yes,no,yes,$$$,denver,+17206051889,(720) 605-1889
2,UkXP_D2vih-LS5oAaMxRIg,madeline,False,20,restaurants,4.9,39.725727,-104.971430,no,no,no,Desconocido,denver,Desconocido,Desconocido
3,lyit8GGKG4AyxO3CrTQErQ,jack’s modern steakhouse,False,252,bars,4.6,39.689850,-104.980581,no,no,no,$$$,denver,+17208685800,(720) 868-5800
4,2wrS0h8iXFZTr4p0egCLjQ,west saloon & kitchen,False,1098,american,4.5,39.744030,-104.990440,yes,yes,yes,$$,denver,+13038253690,(303) 825-3690
5,svJWwW0ilssyqk_UML0mUg,work & class,False,1893,new american,4.5,39.757610,-104.986040,yes,no,no,$$,denver,+13032920700,(303) 292-0700
6,0jTb4q8Ezil_tXkbZf-HRQ,rougarou,False,59,southern,4.7,39.756240,-104.975920,no,no,no,Desconocido,denver,Desconocido,Desconocido
7,ywFvkNZVJoXUQbZoq7fr1w,rioja,False,2930,new american,4.3,39.747808,-104.999331,no,no,yes,$$$,denver,+13038202282,(303) 820-2282
8,i8VF3q7dTszCcigJSMcJzQ,angelo’s taverna,False,2033,italian,4.4,39.725523,-104.979224,yes,no,yes,$$,denver,+13037443366,(303) 744-3366
9,iS9j0iSOhRzBBYJdzzuZFQ,point easy,False,94,new american,4.6,39.756880,-104.963220,no,no,no,Desconocido,denver,+13032335656,(303) 233-5656
10,jML03gtMkgIFWX9Iium4Xg,safta,False,1089,middle eastern,4.4,39.768936,-104.980352,yes,no,no,$$$,denver,+17204082444,(720) 408-2444
11,x0rVT3E__00xg99uGr0tjg,happy camper,False,1232,pizza,4.2,39.762230,-105.006760,yes,no,yes,$$,denver,+17202591044,(720) 259-1044
12,InKe17J_fpqDBorFxEsUXw,ma's kitchen next door,False,78,pan asian,4.7,39.740336,-104.959570,no,no,no,Desconocido,denver,+13037368037,(303) 736-8037
13,gagUrh3806qc5hZ14F0Odw,denver biscuit co. - colfax,False,4998,sandwiches,4.5,39.740340,-104.949128,yes,no,yes,$$,denver,+13033393977,(303) 339-3977
14,fHR1VVGarB17xh56bxbUcg,revival denver public house,False,247,cocktail bars,4.1,39.743119,-104.978921,yes,no,yes,Desconocido,denver,+17205247867,(720) 524-7867
15,vFNCul1JCv4yBtTqdoxscQ,olivia,False,310,italian,4.6,39.711269,-104.973182,yes,no,no,Desconocido,denver,+13039990395,(303) 999-0395
16,XlNLa_kiknuAfm29wXO8KA,pig and tiger,False,65,taiwanese,4.4,39.750820,-104.984700,no,no,no,Desconocido,denver,+17206967979,(720) 696-7979
17,YxeTWblmRB3m7egJzgAJCg,pony up,False,480,sandwiches,4.5,39.752420,-104.996250,yes,no,yes,$$,denver,+17207108144,(720) 710-8144
18,Xksk_U8F756DUVFCz134Tw,the wolf's tailor,False,337,new american,4.4,39.772770,-105.010880,yes,no,yes,$$$$,denver,+17204566705,(720) 456-6705
19,UxCQdVtMhGSiZrcGJd12Ig,alma fonda fina,False,308,mexican,4.7,39.758115,-105.011670,no,no,no,Desconocido,denver,+13034559463,(303) 455-9463
20,LX8nS1dlW7MEZDDEmVcyGw,root down,False,4192,new american,4.4,39.763060,-105.005600,yes,no,no,$$,denver,+13039934200,(303) 993-4200
21,6-MYTEofJo7jmdoTfuVIHA,nana's dim sum & dumplings,False,645,dim sum,4.5,39.763536,-105.010744,yes,no,yes,Desconocido,denver,+17207694051,(720) 769-4051
22,h5ohyi4dOsioSsvSj3398A,monarch,False,8,pizza,5.0,39.743040,-104.984005,no,no,no,Desconocido,denver,Desconocido,Desconocido
23,pFuMzFgNKdEWXi0ckj0ivw,corsica wine bar,False,261,wine bars,4.3,39.761415,-104.983897,no,no,no,Desconocido,denver,+17209942020,(720) 994-2020
24,0-O-xCaxbO-ftWVEYVrRlg,barcelona wine bar,False,1269,tapas/small plates,4.3,39.761334,-104.981361,yes,no,no,$$,denver,+13038163300,(303) 816-3300
25,kRiwvntcXKDPdtpYKcGPhg,onefold,False,1245,breakfast & brunch,4.3,39.744660,-104.969340,yes,no,yes,$$,denver,+13039540877,(303) 954-0877
26,6F4_oM9oRzBDc7KeTEtvcw,wild corgi pub,False,149,pubs,4.3,39.736970,-104.972260,yes,no,yes,Desconocido,denver,+13038327636,(303) 832-7636
27,PHs8DL9UUOOehhUtE5b1qw,corinne denver,False,766,breakfast & brunch,4.0,39.744068,-104.993949,yes,no,yes,$$,denver,+17209961555,(720) 996-1555
28,L3uHyn2eMYOur3CRLkg8sA,mezcaleria alma,False,117,wine bars,4.8,39.758050,-105.011595,no,no,no,Desconocido,denver,+13034841471,(303) 484-1471
29,SND7k63zO_UuV-Sr--knpA,painted rino kitchen + bar,False,10,breakfast & brunch,4.3,39.771660,-104.977695,no,no,no,Desconocido,denver,+17208067251,(720) 806-7251
30,KeRN5k0IFBEdGhDTRNZe_g,the porchetta house,False,165,sandwiches,4.7,39.740399,-104.969415,yes,no,yes,$$,denver,+13038617333,(303) 861-7333
31,EjNI-dNAMrYxKgUIkqeqhg,guard and grace modern steakhouse,False,2135,steakhouses,4.5,39.747956,-104.989075,yes,no,yes,$$$$,denver,+13032938500,(303) 293-8500
32,QWWfOQ9yrWDuZwP-mgL1Ig,lucina eatery & bar,False,170,latin american,4.6,39.750170,-104.917760,no,no,no,$$$,denver,+17208141053,(720) 814-1053
33,rdZPV9r3WPlke0ZO1mRcNA,pete's kitchen,False,971,greek,3.9,39.739781,-104.963662,no,no,yes,$$,denver,+13033213139,(303) 321-3139
34,R5sNCLBmMp61uYui1Wp5UA,toki ramen and sushi,False,35,ramen,4.9,39.691413,-104.940372,yes,no,yes,Desconocido,denver,Desconocido,Desconocido
35,LLxpJh4yyExw1K7GJsB2zw,a5 steakhouse,False,321,steakhouses,4.3,39.750279,-105.001549,no,no,no,Desconocido,denver,+13036230534,(303) 623-0534
36,43DCpM0VKoFY-Mnv30RhLQ,kyuu,False,14,japanese,4.8,39.743054,-104.971178,no,no,no,Desconocido,denver,+17207285226,(720) 728-5226
37,c3QuHjgIkESyn_eD4EiACA,nocturne,False,429,jazz & blues,4.6,39.759590,-104.984512,yes,no,no,$$$,denver,+13032953333,(303) 295-3333
38,-mLKEN6U1vmBs8IxxBVaEw,fish n beer,False,528,seafood,4.6,39.767199,-104.974027,yes,no,no,$$,denver,+13032483497,(303) 248-3497
39,FIabjV94L_-HH9w8rT6j3Q,carne - argentina street food,False,116,sandwiches,4.7,39.720498,-104.998408,yes,no,yes,$$,denver,+17205103999,(720) 510-3999
40,qwklKpOZFgOOjMm3-NMzNA,burndown,False,228,bars,4.1,39.708036,-104.987242,no,no,no,$$,denver,+17208993827,(720) 899-3827
41,NOkJ14ltntgE4XWS5AgOSA,the brutal poodle,False,624,bars,4.5,39.680880,-104.987846,yes,no,yes,$$,denver,+17203796281,(720) 379-6281
42,7A70YVFJBWN6fbCYQPpNIA,brasserie brixton,False,165,french,4.4,39.768309,-104.966288,no,no,no,Desconocido,denver,+13035930951,(303) 593-0951
43,Lu6Uk12Rg0jkUQUzcHLWFw,fox and the hen,False,429,breakfast & brunch,4.4,39.762136,-105.014174,no,no,no,$$,denver,+13038626795,(303) 862-6795
44,s87TW7XplzOqu66TxIyw3g,margot denver,False,58,new american,4.7,39.688441,-104.980620,no,no,no,Desconocido,denver,+17203908785,(720) 390-8785
45,GxCgbV8rB7ORs8g0J2nMwQ,noodles by nina,False,145,noodles,4.5,39.742908,-104.969253,no,no,no,$$,denver,+13039555858,(303) 955-5858
47,X3_hbxeKNXChhvnAF7RnRQ,30forth kitchen,False,6,new american,5.0,39.758766,-104.963388,no,no,no,Desconocido,denver,+17202278209,(720) 227-8209
48,ewCTNd0cUPMY32kD5opphw,chubby cattle hotpot & sushi - denver,False,1681,hot pot,4.2,39.716748,-104.987193,yes,no,yes,$$$,denver,+17206502541,(720) 650-2541
49,CQNv4SXqFltcwNsx-qHbLQ,steuben's uptown,False,3476,diners,4.0,39.743490,-104.980170,yes,no,yes,$$,denver,+13038301001,(303) 830-1001
50,jVOAZe9L3Kwx9Ze-UhT3_w,odyssey italian restaurant,False,1536,sicilian,4.3,39.725781,-104.979706,yes,no,yes,$$,denver,+13033180102,(303) 318-0102
51,zN55MOWDOYAUhJHRVBx9EA,paperboy denver,False,72,breakfast & brunch,4.3,39.762003,-105.039149,no,no,no,Desconocido,denver,+17202794603,(720) 279-4603
52,JJiugrBcZrNpX0ueUBuvrg,cherry cricket - cherry creek,False,3535,burgers,4.0,39.719634,-104.956348,yes,no,yes,$$,denver,+13033227666,(303) 322-7666
53,k1mGLPBSaUhZKem1KrXLJQ,stout street social,False,1747,new american,4.0,39.744288,-104.994947,yes,no,yes,$$,denver,+17202149100,(720) 214-9100
54,ZnhMS3NichhkEPUmTqJfbw,mantra cafe,False,72,indian,4.6,39.734877,-104.987811,yes,no,yes,Desconocido,denver,+17207615972,(720) 761-5972
55,8wmfcpBTOn6BwC1YPvOmDA,rōmyō,False,28,italian,4.3,39.747612,-104.999843,no,no,no,Desconocido,denver,Desconocido,Desconocido
56,sU4K-0uTlhvn3OTGqnKamw,heretik,False,23,spanish,4.7,39.759704,-104.986211,no,no,no,Desconocido,denver,+17202579168,(720) 257-9168
57,yXVJ_K6vdpM3PwfHfkyn5g,mister oso,False,501,tacos,4.1,39.764240,-104.978480,yes,no,yes,$$,denver,+17206776454,(720) 677-6454
58,NGiJYiciQao11MXwl-56pg,kawa ni,False,254,izakaya,4.5,39.761783,-105.009968,no,no,no,$$$,denver,+17207123371,(720) 712-3371
59,lSndVTQ9XCpz9fDMFpSBug,carne rino,False,113,steakhouses,4.4,39.758800,-104.985300,no,no,no,Desconocido,denver,+13039531558,(303) 953-1558
60,BHpQiNX5LF79RHTCng8TqQ,nola voodoo tavern,False,332,cafes,4.5,39.764695,-104.960311,yes,no,yes,$$,denver,+17203899544,(720) 389-9544
61,2gGWFWp3DIjxzE3lVFZtNA,little wolf,False,50,whiskey bars,4.8,39.777090,-105.034440,no,no,no,Desconocido,denver,+17207039220,(720) 703-9220
62,VxSKu6BxKiT1jRr6arsLLg,cherry cricket - downtown,False,535,sports bars,4.1,39.756308,-104.991220,yes,no,no,$$,denver,+13032973644,(303) 297-3644
63,DFzFzU6iHbXZtTGu1mN4IA,stellar jay,False,72,restaurants,4.3,39.740315,-104.990945,no,no,no,$$$,denver,+13032566381,(303) 256-6381
64,tnFs9EImexnBdlwZjmEfcw,horse & tiger,False,9,comfort food,5.0,39.778458,-104.983130,no,no,no,Desconocido,denver,+13033512377,(303) 351-2377
65,viYTcIvA2l_iSqrNpWeTdA,yahya's mediterranean grill & pastries,False,683,mediterranean,4.6,39.740169,-104.960767,yes,no,yes,$$,denver,+17205328746,(720) 532-8746
66,s0_kPOB-ywdGUMdqHw5uTg,dearly departed,False,14,cocktail bars,4.9,39.759241,-105.010751,no,no,no,Desconocido,denver,+13034793124,(303) 479-3124
67,6VE5QY2ULcc8JHB-eLARag,alteño,False,100,mexican,4.5,39.720399,-104.955998,no,no,no,Desconocido,denver,+13035324999,(303) 532-4999
68,_fcKVnAc2n2Nj5vX-vcLAA,aguanile,False,14,puerto rican,4.6,39.708693,-104.992625,no,no,no,Desconocido,denver,+13033515975,(303) 351-5975
69,u0lEXYd_cdf2_Zg99rSM9w,vine street pub & brewery,False,1003,american,4.2,39.743400,-104.962010,no,no,no,$$,denver,+13033882337,(303) 388-2337
70,fdipNvAALQxjJWNz-USidQ,hillstone restaurant,False,780,new american,3.7,39.721141,-104.958424,no,no,yes,$$$,denver,+13033334688,(303) 333-4688
71,biju9F9GKy0Ogn3YotSZ4A,wildflower,False,231,cocktail bars,4.6,39.767589,-105.003796,no,no,no,Desconocido,denver,+17207066615,(720) 706-6615
72,O2DoP-SUVov0qwAn1atMbg,champagne tiger,False,79,french,4.5,39.740206,-104.979676,no,no,no,Desconocido,denver,+13039420593,(303) 942-0593
73,swPiklhuXaMLnw5Rh2y7Ew,rhein haus,False,622,bars,3.7,39.748355,-105.000585,yes,no,yes,$$,denver,+13037315374,(303) 731-5374
74,gGXnG-Rf5UUr6wT8krXT5w,williams & graham,False,1136,american,4.4,39.761950,-105.011000,no,no,no,$$,denver,+13039978886,(303) 997-8886
75,m3ifi6O7ntMta8102eVgow,uchi denver,False,1140,japanese,4.5,39.756926,-104.985261,yes,no,no,$$$$,denver,+13034441922,(303) 444-1922
76,IHS_gAK8AEYKqs6RCQXSEw,florence supper club,False,58,italian,4.2,39.709730,-104.980690,no,no,no,Desconocido,denver,Desconocido,Desconocido
77,OGwS_BIkHSWdcvQRdW_kfA,four friends kitchen,False,2217,southern,4.3,39.757478,-104.900572,yes,no,no,$$,denver,+13033888299,(303) 388-8299
78,JRNo_7YSPyVBTMNpu8ZkLA,the velvet cellar,False,118,cocktail bars,4.4,39.750965,-105.001631,no,no,no,$$$,denver,+17206769116,(720) 676-9116
79,Z8vO_mf1V09QDUPdyqJ6og,linger,False,4438,asian fusion,4.1,39.759540,-105.011390,yes,no,yes,$$,denver,+13039933120,(303) 993-3120
80,6fJltLxQcLgO0owitrzlBQ,cuba cuba cafe & bar,False,1033,cuban,4.4,39.735085,-104.993179,yes,no,yes,$$,denver,+13036052822,(303) 605-2822
81,pm-Rc3kcCuT5RGbNIldinA,acova,False,736,new american,4.3,39.767777,-105.004247,yes,no,yes,$$,denver,+13037362718,(303) 736-2718
82,uQd0TZKBprBXxF1aGSIAIA,dew drop inn,False,89,gastropubs,4.5,39.743400,-104.973819,no,no,no,Desconocido,denver,+17206124160,(720) 612-4160
83,T0oDpWqZWOjli02HuIO3DQ,potager,False,500,new american,3.8,39.733960,-104.975420,no,no,yes,$$$,denver,+13038325788,(303) 832-5788
84,kI5oOBAGS-Vo4chwmgOVmQ,cart-driver,False,830,pizza,4.5,39.757530,-104.986214,yes,no,yes,$$,denver,+13032923553,(303) 292-3553
85,nMagfV2RQrH0N0EZ46AHRg,cimera,False,71,latin american,3.7,39.768434,-104.980181,no,no,no,Desconocido,denver,+17204676913,(720) 467-6913
86,_2vT7PH78NIqleshrnb19w,brutø,False,147,tapas/small plates,4.3,39.752781,-104.996823,yes,no,yes,Desconocido,denver,+17203252195,(720) 325-2195
87,KwmKhdWpcIzypdjAUNrc7w,mercantile,False,1423,new american,4.2,39.753615,-104.999707,yes,no,no,$$,denver,+17204603733,(720) 460-3733
88,PUhHWM8_rbwUD-8gzfCSOg,sắp sửa,False,252,vietnamese,4.3,39.739794,-104.956637,no,no,no,Desconocido,denver,+13037362303,(303) 736-2303
89,WTe8uL6vF1ZuKAeJIvxR8w,savina's,False,2222,mexican,4.1,39.744758,-104.987827,yes,no,yes,$$,denver,+13034338300,(303) 433-8300
90,QZAZrHljjy8qh1QXacT0tg,olive & finch,False,945,new american,4.2,39.743060,-104.968920,yes,no,yes,$$,denver,+13038328663,(303) 832-8663
91,XWqdMrdt8OJWT6ECMvavPw,the plimoth,False,406,italian,4.4,39.757143,-104.958879,yes,no,no,$$$,denver,+13032971215,(303) 297-1215
92,HlL84_OVXvKHndkCqQJn2w,kkoki korean bbq,False,99,korean,4.6,39.754358,-105.004652,no,no,no,Desconocido,denver,+13039532422,(303) 953-2422
93,wL04ets5vd2CGxbzj3ii5w,blue agave grill,False,851,seafood,4.1,39.749031,-104.996825,yes,no,yes,$$,denver,+17205508389,(720) 550-8389
94,46gG3_h3zwFfkf4_183Ydg,somebody people,False,362,wine bars,4.5,39.695218,-104.987801,yes,no,no,$$$,denver,+17205025681,(720) 502-5681
95,izi7Hh5Kz7iC4gEjQ4BxSw,dear emilia,False,35,italian,4.3,39.772372,-104.978388,no,no,no,Desconocido,denver,Desconocido,Desconocido
96,zvxXmGRW464sEe-8TVrPGQ,ni tuyo,False,198,tacos,4.6,39.702780,-104.959110,no,no,no,$$,denver,+13032828896,(303) 282-8896
97,bb_VNwJQLzao_3HSGx6B9g,postino 9co,False,416,wine bars,4.5,39.729774,-104.940273,yes,no,yes,$$,denver,+17202625474,(720) 262-5474
98,5lCzYPnAoNNlAZxW3rr_RA,satchel's on 6th,False,233,new american,3.9,39.725450,-104.966740,yes,no,no,$$,denver,+13033992560,(303) 399-2560
99,Wrbu8rpUiy63RL4slvJCAw,xiquita,False,107,mexican,4.4,39.746002,-104.980866,no,no,no,Desconocido,denver,+17202872701,(720) 287-2701
100,Y8Np2emyG1l8yyg3jWovAQ,jovanina's broken italian,False,530,italian,4.2,39.749847,-104.999792,yes,no,yes,Desconocido,denver,+17205417721,(720) 541-7721
101,9aZRlwqxx0r709kgOGeCcw,uncle,False,393,ramen,4.3,39.714970,-104.981590,yes,no,no,$$,denver,+17206381859,(720) 638-1859
102,E4HzQMzTSWlRjc8_DCnOYg,postino broadway,False,578,wine bars,4.5,39.719153,-104.987691,yes,no,yes,$$,denver,+13033517000,(303) 351-7000
103,K_LyxTyTfafUytd75mMmMg,ultreia,False,526,tapas bars,4.1,39.753050,-104.999950,yes,no,yes,$$$,denver,+13035341970,(303) 534-1970
104,lqNe_QMrAyZLnEr06F9S_w,jax fish house & oyster bar,False,1280,seafood,4.3,39.752120,-104.998590,yes,no,yes,$$,denver,+13032925767,(303) 292-5767
105,IbCPSViliNokpqUsMQ_nbg,la chiva,False,341,colombian,4.2,39.690250,-104.987269,yes,no,yes,$$,denver,+17203899847,(720) 389-9847
106,hVREDpdqoOiJvaRCiyMO1g,fino,False,23,wine bars,3.7,39.740402,-104.952019,no,no,no,Desconocido,denver,+13032844545,(303) 284-4545
107,guyzZWM2a4qZxQOvMlFBQg,temaki den,False,423,sushi bars,4.6,39.768565,-104.979803,yes,no,yes,$$$$,denver,+13032000530,(303) 200-0530
108,7yYkXMzgL-zIh-xZB6C7Xg,sauvage,False,12,food trucks,4.3,39.734283,-104.958445,no,no,no,Desconocido,denver,+13182720015,(318) 272-0015
109,3IHkyNrJfm_CLZ-qWtsdhQ,nola jane restaurant & bar,False,274,cajun/creole,4.1,39.748625,-105.000268,yes,no,yes,$$,denver,+17205921942,(720) 592-1942
110,pnY1m8aBusUCqgD1rUcLyw,panzano,False,1321,italian,4.3,39.747833,-104.992822,yes,no,yes,$$$,denver,+13032963525,(303) 296-3525
111,iVq2BYW5u58mGLlrevpbTw,water grill - denver,False,431,seafood,4.3,39.750810,-104.997340,no,no,no,$$$,denver,+13037275711,(303) 727-5711
112,LVF3bhuKZpuy-GQYhzmZsA,riot bbq,False,144,barbeque,4.6,39.676981,-104.992041,yes,no,yes,$$,denver,+13038726862,(303) 872-6862
113,dlGpaDSUdureTrW_oi9gig,toad kitchen,False,2,asian fusion,5.0,39.739174,-104.975590,no,no,no,Desconocido,denver,Desconocido,Desconocido
114,XluydvQpT75gjiuRSclhcQ,the denver central market,False,692,bakeries,4.4,39.759364,-104.984548,no,no,no,$$,denver,Desconocido,Desconocido
115,iM8ijTk7rpzcwGAIm7thwg,gattara,False,247,italian,4.1,39.744387,-104.983221,yes,no,yes,$$,denver,+13033187272,(303) 318-7272
116,MvS8MEgkEvhA9mv-y5Wtow,dio mio,False,451,italian,4.0,39.764790,-104.976780,yes,no,yes,$$,denver,+13035621965,(303) 562-1965
117,SP58V3g_vD92c7Njh6NLiw,apres govnr's park,False,60,venues & event spaces,4.8,39.727133,-104.982160,no,no,no,Desconocido,denver,+17206179400,(720) 617-9400
118,IqC4v53GgZce6TbLqyFa7Q,bull & bush,False,1154,american,4.0,39.703057,-104.932560,no,no,yes,$$,denver,+13037590333,(303) 759-0333
119,FBqPcIryM6R-k1KV7WLwOw,death & co,False,559,cocktail bars,4.2,39.757287,-104.986506,yes,no,no,$$$,denver,+17203302660,(720) 330-2660
120,QAMR-ujpiN4nuggIDMBXaA,difranco’s,False,675,italian,4.4,39.731076,-104.986340,yes,no,yes,$$,denver,+17202531244,(720) 253-1244
121,fdeVBWzB4jZV7QupbQSXUg,urban farmer denver,False,769,steakhouses,4.0,39.752313,-104.999166,yes,no,no,$$$,denver,+13032626070,(303) 262-6070
122,EOh9f0jI92sZZa76QLKb-g,beckon,False,174,new american,4.5,39.761151,-104.982338,no,no,no,$$$$,denver,+13037490020,(303) 749-0020
123,Ttk8uzixI-qX8LhdHINV9A,toro,False,365,latin american,4.4,39.718957,-104.955457,yes,no,yes,Desconocido,denver,+13032533000,(303) 253-3000
124,jx5kzkP_9zwh9BW0WVPAWw,osteria marco,False,1976,italian,4.1,39.748190,-104.998970,yes,no,yes,$$$,denver,+13035345855,(303) 534-5855
125,kDFzP_99yO-iQZRDfHJ30Q,the crypt,False,64,dive bars,4.1,39.743060,-104.967900,yes,no,yes,Desconocido,denver,+17205429543,(720) 542-9543
126,kfTdkvBUiAqqzISm_cq23A,hop alley,False,620,chinese,4.1,39.767020,-104.974180,yes,yes,no,$$$,denver,+17203798340,(720) 379-8340
127,0718djzuQihUiWsjriPjZg,velada,False,1,tapas/small plates,5.0,39.772012,-104.976394,no,no,no,Desconocido,denver,+17207380760,(720) 738-0760
128,HRBLmk4cyiwaIGuZRPEGBg,woodie fisher kitchen & bar,False,380,new american,4.0,39.757698,-104.999002,yes,no,yes,$$$,denver,+17206431909,(720) 643-1909
129,PIg2YoMC44y-K8IT0-vkdw,yuan wonton,False,217,food trucks,4.5,39.757951,-104.927872,no,no,no,$$,denver,+13033205642,(303) 320-5642
130,n18mJPI6mQfBJEp8UrITyw,blue pan pizza,False,996,pizza,4.4,39.735245,-104.945715,yes,no,no,$$,denver,+17205190944,(720) 519-0944
131,73GqioIw-vz3oNmb-g9Kew,major tom,False,48,tapas/small plates,4.2,39.761260,-104.982360,no,no,no,Desconocido,denver,+13038489777,(303) 848-9777
132,AVfpz6GAPKx659IujpCFbQ,odie b's - rino,False,63,burgers,4.5,39.771706,-104.969594,no,no,no,Desconocido,denver,Desconocido,Desconocido
133,N_tX1pJz92Ls-4sMQvMLpA,postino lohi,False,1060,new american,4.5,39.761447,-105.010690,yes,yes,yes,$$,denver,+13034336363,(303) 433-6363
134,NwkErPU8Y7bgmndQSbVGqA,chez maggy,False,269,french,4.1,39.749980,-104.997710,no,no,no,Desconocido,denver,+17207949544,(720) 794-9544
135,yStfRVi_w8jxIjRExfviEA,el five,False,1224,tapas/small plates,4.1,39.759127,-105.011484,yes,no,no,$$$,denver,+13035249193,(303) 524-9193
136,NkjpBZfR4455T7uWvtRN-w,bao brewhouse,False,885,dim sum,3.9,39.747747,-105.000030,yes,yes,yes,$$,denver,+17203248675,(720) 324-8675
137,ENDOWXUYlg_EBwvflvlXLQ,kealoha's bbq,False,111,barbeque,4.6,39.743873,-104.990433,yes,no,yes,$$,denver,+18089905850,(808) 990-5850
138,psESMQAg6u2MNnY5DzGcDQ,appaloosa grill,False,1276,new american,3.9,39.744355,-104.991012,yes,no,yes,$$,denver,+17209321700,(720) 932-1700
139,jsra5k3lfG98mskRwpIwKQ,teachers' lounge food + drink,False,111,new american,3.8,39.740993,-104.995245,no,no,no,Desconocido,denver,+17207227035,(720) 722-7035
141,9ZA3ixRK1v0pu_RCo-XGmw,tamayo by chef richard sandoval,False,1458,mexican,3.8,39.747254,-104.999435,yes,no,yes,$$$,denver,+17209461433,(720) 946-1433
142,KirNvv8CPBgcX_Bd0X56gQ,lo stella ristorante,False,432,italian,3.9,39.734570,-104.990410,yes,no,yes,$$$,denver,+13039612277,(303) 961-2277
143,lpiXtr3y25zPlnS6VFFa7Q,stowaway kitchen,False,494,breakfast & brunch,4.5,39.758620,-104.986610,yes,no,yes,$$,denver,+17206362374,(720) 636-2374

In [22]:
#Reservation
Dic_res=dict(Cantidad = dt_restaurant_YELP['restaurant_reservation'].value_counts(), Porcentaje = dt_restaurant_YELP['restaurant_reservation'].value_counts(normalize = True)*100)
Res_Table = pd.DataFrame(Dic_res)
Res_Table= Res_Table.reindex(['no','yes'])
Res_Table.loc['Total']=Res_Table.sum()
print(Res_Table)
#Delivery
Dic_del=dict(Cantidad = dt_restaurant_YELP['delivery'].value_counts(), Porcentaje = dt_restaurant_YELP['delivery'].value_counts(normalize = True)*100)
Del_Table = pd.DataFrame(Dic_del)
Del_Table= Del_Table.reindex(['no','yes'])
Del_Table.loc['Total']=Del_Table.sum()
print(Del_Table)
#Pickup
Dic_pic=dict(Cantidad = dt_restaurant_YELP['pickup'].value_counts(), Porcentaje = dt_restaurant_YELP['pickup'].value_counts(normalize = True)*100)
Pic_Table = pd.DataFrame(Dic_pic)
Pic_Table= Pic_Table.reindex(['no','yes'])
Pic_Table.loc['Total']=Pic_Table.sum()
print(Pic_Table)

                        Cantidad  Porcentaje
restaurant_reservation
no                         190.0   96.938776
yes                          6.0    3.061224
Total                      196.0  100.000000
          Cantidad  Porcentaje
delivery
no            85.0   43.367347
yes          111.0   56.632653
Total        196.0  100.000000
        Cantidad  Porcentaje
pickup
no         103.0    52.55102
yes         93.0    47.44898
Total      196.0   100.00000